import LocalizedStrings from 'react-native-localization';
import images from './src/theme/Images';

export let LanguageManager = new LocalizedStrings({
  English: {
    assetsNotFound:'Assets not found',
    Huobi: 'HTX Exchange',
    SaitaDex: 'SaitaDex',
    SelectProvider: 'Select Provider',
    buySell: 'Buy/Sell',
    invest: 'Invest',
    sell: 'Sell',
    enterhere: 'Enter here',
    cardsetting: 'Card Settings',
    cardpassword: 'Change Password',
    cardlogout: 'Logout',
    forgot: 'Forgot Password',
    newpassword: 'New Password',
    enternewpassword: 'New Password',
    oldpassword: 'Old Password',
    confirmpassword: 'Confirm Password',
    dateOfBirth: 'Date Of Birth',
    documentType: 'Document Type',
    nationality: 'Nationality',
    documentNo: 'Document Number',
    frontID: 'Front ID Card',
    selfieWithId: 'Selfie With ID Card',
    signaturePhoto: 'Signature Photo',
    EmergencyName: 'Emergency Contact Name',
    EnergencyNumber: 'Emergency Contact Number',
    deposit: 'Deposit',
    otp: 'OTP Verification',
    otptext: 'Enter the 6 Digit OTP to verify your email address',
    applyCard: 'Apply for the card',
    blackCard: 'Get SaitaCard Black',
    blackCardActivated: 'Activated SaitaCard Black',
    saitaCard: 'Get SaitaCard',

    uploadIdCard: 'Upload Your ID Card',
    uploadSelfieIdCard: 'Upload Your Selfie With ID Card',
    goldCard: 'Get SaitaCard Gold',
    diamondCard: 'Get SaitaCard Diamond',
    PayusingSaitaPro: 'Pay using USDT(ERC20)',
    Payusinggateway: 'Pay using Visa/Mastercard(Epay)',
    retryKyc: 'Retry KYC Process',
    contactepay: 'Contact Epay Support team',
    sortBy: 'Ordenar por',
    lets: "Let's get started",
    enterCorrectPin: 'Please enter the correct PIN',
    withdrawalAddress: 'Withdrawal Address',
    from: 'From',
    updateWalletName: 'Update',
    yourLiquid: 'Your liquidity',
    addLiquidReceiveLp: 'Add liquidity to receive LP tokens',
    transactions: 'Transactions',
    noCoinEnabled: 'No Coins Enabled',
    enterValue: 'Enter value',
    faceIdTouchOId: 'Face Id / Touch Id',
    resetYourPin: 'Reset your PIN',
    congratulationsForCreateWallet: 'Your wallet is ready.',//Change
    walletCreatedSuccessfully: 'Sed ut perspiciatis unde omnis iste natus error \n sit voluptatem accusantium doloremque \n laudantium, totam rem aperiam,',//Change
    decimal: 'Decimals',
    symbol: 'Symbol',
    contractAddress: 'Contract Address',
    enterContractAdress: 'Enter Contract Address',
    selectNetwork: 'Select Network',
    seeLess: 'See Less',
    slippageTolerance: 'Slippage tolerance',
    transactionTimeout: 'Transaction Timeout',
    recoveryPhrase: 'Recovery Phrase',
    backupWallet: 'Backup Wallet',
    assets: 'Assets',
    continue: 'Continue',
    search: 'Search',
    ResetCreatePIN: 'Reset Create Pin',
    shareAddress: 'Share Address',
    withDrawlAddress: 'Withdrawal Address',
    // shareAddress: 'Share Address',
    // assets: 'Assets',
    // continue: 'Continue',
    // search: 'Search',
    // ResetCreatePIN: 'Reset Create Pin',
    approveCoin: 'Approve ETH',
    pricesAndPool: 'Prices and Pool Share',
    stake: 'Stake',
    getYourStaking: 'Get Your Staking',
    duration: 'Duration',
    days: 'Days',
    lockedAmount: 'Locked Amount',
    max: 'Max',
    apy: 'APY',
    lockInPeriod: 'Lock in Period',
    finalRewards: 'Final Rewards',
    enterAmount: 'Enter Amount',
    myEarnings: 'Saitama Balance',
    Rewards: 'Rewards',
    term: 'Term',
    action: 'Action',
    claimed: 'Claimed',
    unStake: 'Unstake',
    daysLeft: 'Days Left',
    receive: 'Receive',
    backupOptions: 'Backup Options',
    exportPublicKeys: 'Export Public Keys',
    wallets: 'Wallets',
    addNewWallet: 'Add New Wallet',
    To: 'To',
    seeAll: 'See All',
    upLoadCsv: 'Upload CSV FILE',
    bulkTransfer: 'Bulk Transfer',
    selectToken: 'Select Token',
    removeLiquidity: 'Remove Liquidity',
    remove: 'Remove',
    listOfRecipients: 'List of Recipients',
    buyBtc: 'Buy BTC',
    defi: 'DeFi',
    account: 'Account',
    theme: 'Theme',
    mode: 'Mode',
    getSupported: 'Get Supported',
    saitaProSupport: 'SaitaPro Support',
    connectWithUs: 'Connect With Us',
    instagram: 'Instagram',
    facebook: 'Facebook',
    twitter: 'Twitter',
    Telegram: 'Telegram',
    discord: 'Discord',
    Logout: 'Logout',
    title1: 'Create',
    title2: 'Pin',
    UNIQUEPIN: 'UNIQUE PIN',
    Touchid: 'Touch ID',
    Faceid: 'Face ID',
    Biometrics: 'Biometrics',
    Back: 'Back',
    submit: 'Submit',
    Approved: 'Approved',
    EnterPin: 'Enter PIN',
    ConfirmPin: 'Confirm PIN',
    CreatingPin: 'Creating a PIN',
    CreatePin: 'Create a PIN',
    PinReq: 'This 6 digit pin will be required\nto access the wallet',
    ImportWallet: 'IMPORT\nWALLET',
    CreateWallet: 'CREATE\nWALLET',
    needHelp: 'Need help deciding?',
    walletText:
      'On SaitaPro you can create a\nnon-custodial wallet or import an existing\none using your security phrase.',
    Import: 'Import',
    Wallet: 'Wallet',
    pasteText:
      'Paste or type your security phrase in correct order with words divide by spaces',//change
    name: 'Name',
    fullName: 'Full Name',
    firstName: 'First Name',

    lastName: 'Last Name',

    phone: 'Phone Number',
    address1: 'Address 01',
    address2: 'Address 02',
    state: 'State',
    country: 'Country',
    zipcode: 'Zip Code',
    emailid: 'Email ID',
    password: 'Password',
    applyfees: 'Apply & Pay Fees',
    apply: 'Apply',
    blackCardheading: 'Black Card',
    diamondCardheading: 'Diamond Card',
    goldCardheading: 'Gold Card',
    NameWallet: 'Enter wallet name',//Change
    myWallet: 'My Wallet',//Change
    selectColor: 'Select a color',
    getStart: 'Let’s get started',
    secure: 'Secure',
    next: 'Next',
    takeNote:
      'Take note of your secret phrase and keep it some where safe, if you lose this phrase you may not be able to access your wallet.',
    copyPhrase: 'Copy phrase',
    verify: 'Verify',
    phrase: 'Phrase',
    correctOrder:
      'Click on the words in the correct order of your security phrase shown in the previous screen.',
    swap: 'Swap',
    get: 'Get',
    send: 'Send',
    buy: 'Buy',
    staking: 'Staking',
    multiSend: 'Bulk\nTransfer',
    noCoinFound: 'No coin found',
    Hot: 'Hot',
    Gainer: 'Gainer',
    Loser: 'Loser',
    Vol: '24h Volume',
    Coin: 'Coins',
    LastPrice: 'Last Price',
    HrChange: '24h Change',
    noGraphFound: 'No graph found',
    SaitamaInu: 'Saitama Inu',
    Home: 'Home',
    Market: 'Market',
    Wallet_: 'Wallet',
    Settings: 'SETTINGS',
    searchToken: 'Search   ',
    searchUrl: 'Search or enter website url ',
    Finance: 'Finance',
    Exchanges: 'Exchanges',
    Games: 'Games',
    NFTs: 'NFTs',
    ok: 'Ok',
    Tokens: 'Tokens',
    Manage: 'Manage',
    Security: 'Security',
    History: 'History',
    BackupOption: 'Backup Wallet',
    MultiWallet: 'Manage Wallet',
    Preferences: 'Currency Preferences',
    contactUs: 'Connect With Us',
    Logout: 'Logout',
    Notifications: 'Notifications',
    NoNoti: 'No Notifications',
    select: 'Select',
    searchBlock: 'Search Blockchain',
    NoHistory: 'No Transaction Found !',
    addNewContact: 'Add New Contact',
    nameYourContact: 'Name Your Contact',
    enterNameHere: 'Enter Name here',
    addWalletAddress: 'Add Wallet Address',
    address: 'Address',
    paste: 'Paste',
    saveContact: 'Save Contact',
    addToken: 'Add Token',
    addCustomToken: 'Add Custom Token',
    tokenSymbol: 'Token Symbol',
    ethereum: 'Ethereum',
    binance: 'Binance',
    bitcoin: 'Bitcoin',
    polygon: 'Polygon',
    tokenContactAddress: 'Token Contract Address',
    enterTokenContactAddress: 'Enter Token Contract Address',
    enterTokenSymbol: 'Enter Token Symbol',
    backUpOptions: 'Backup Options',
    showRecoveryPhrase: 'Show Recovery Phrase',
    exportPrivateKeys: 'Export Private Keys',
    changePasscode: 'Change PassCode',
    // enterSixDigitPin: 'Enter 6 Digit PIN',
    // reEnterSixDigitPin: 'Re-Enter the 6 digit Pin to \n access the wallet',

    history: 'History',
    noTransactionFound: 'No Transaction Found !',
    confirm: 'Confirm',
    pin: 'Pin',
    proceed: 'Proceed',
    pinIsRequired: 'This 6 digit pin will be required',
    toAccessWallet: 'to access the wallet',
    transactionFees: 'Transaction Fees',
    advancedOptions: 'Advanced Options',
    slow: 'slow',
    average: 'Average',
    fast: 'Fast',
    totalAmount: 'Total Amount',
    currencyPreference: 'Currency Preferences',
    contactEditedSuccessfully: 'Contact edited successfully',
    errorWhileEditingContact: 'Error while editing contact',
    editContact: 'Edit Contact',
    nameFieldIsRequired: 'Name field is required',
    emailFieldIsRequired: 'Email field is required',
    invalidEmail: 'Entered email is invalid',
    subjectFieldIsRequired: 'Subject field is required',
    messageFieldIsRequired: 'Message field is required',
    addressFieldIsRequired: 'Address field is required',
    transactionLinkRequired: 'Transaction link is required',
    attachScreenshotsRequired: 'Please Attach Screenshots',
    invalidAddress: 'Invalid Address',
    requestSentSuccessfully: 'Request sent successfully',
    errorWhileSendingRequest: 'Error while sending request',
    getInTouch: 'Get in touch',
    forSupport: 'for support',
    supportLine: 'This is the official SaitaPro support channel please fill all the fields and provide links and screenshots when applicable, we will contact you shortly through emails.',//New
    // supportLine1: 'This is official SaitaPro support channel please fill all the fields and provide links and screenshots when applicable, we will contact you shortly through emails',//New
    supportLine2: 'please fill all the fields and provide links and',
    supportLine3: 'screenshots when applicable, we will contact',
    supportLine4: 'you shortly through emails',
    email: 'E-mail',
    subject: 'Subject',
    message: 'Message',
    walletAddress: 'Wallet Address',
    transactionLinks: 'Transaction Links',
    attachScreenshots: 'Attach Screenshots',
    takePhoto: 'Take Photo',
    chooseFromGallery: 'Choose from gallery',
    cancel: 'Cancel',
    done: 'done',
    setAmount: 'Set amount',
    copy: 'Copy',
    share: 'Share',
    shareAddress: 'Share Address',
    publicAddress: 'Public Address',
    recoveryPhraseText:
      'Take note of your secret phrase and keep it some where safe, if you lose this phrase you may not be able to access your wallet.',
    toAccessTheWallet: 'to access the wallet',
    enterPin: 'Enter PIN',
    enterNewPin: 'Enter New PIN',
    creatingAPin: 'Creating a PIN',
    cameraAppPermission: 'Camera App Permission',
    needAccessToCamera: 'SaitaPro use camera to scan crypto addresses, transfer requests and wallet details',
    cameraPermissionDenied: 'Camera permission denied',
    applock: 'Security',
    searchCurrency: 'Search currency',
    wrongPin: 'Wrong Pin',
    lowBalanceAlert: 'Balance too low to send',
    cameraPermissionError: 'Camera permission err',
    longPressToPaste: 'Enter Address',
    contacts: 'Contacts',
    amount: 'Amount',
    available: 'Available',
    transactionFeesBNB: 'Transaction Fees (BNB)',
    transactionFeesSTC: 'Transaction Fees (STC)',
    reset: 'Reset',
    gasPrice: 'Gas Price',
    pleaseEnterGasPrice: 'Please enter Gas Price',
    confirmTransaction: 'Confirm Transaction',
    selectCryptoContact:
      'Select recipient below or add new recipient to send money',
    areYouSure: 'Are you sure you want to delete contact?',
    errorWhileDeletingContact: 'Error while deleting contact',
    contactDeletedSuccessfully: 'Contact Deleted successfully',
    addNew: 'Add New',
    sendCrypto: 'Address Book',//change
    gasLimit: 'Gas Limit',
    pleaseEnterGasLimit: 'Please enter Gas Limit',
    maxPriorityFeeGwei: 'Max Priority Fee (Gwei)',
    enterMaxPriorityFee: 'Please enter Max Priority Fee',
    maxFeeGwei: 'Max Fee (Gwei)',
    maxFee: 'Max Fee',
    stakingPools: 'Staking Pools',
    stakedOnly: 'Staked Only',
    live: 'Live',
    finished: 'Finished',
    shortBy: 'Short by',
    openSoon: 'open soon',
    hot: 'Hot',
    totalStaked: 'Total staked',
    youSend: 'You Send',
    btc: 'BTC',
    youReceive: 'You Receive(Estimate)',
    rate: 'Rate',
    inverseRate: 'Inverse Rate',
    princeImpact: 'Prince Impact',
    gwei: 'Gwei',
    estimateGasFee: 'Estimate gas fee',
    liquidityFee: 'Liquidity Fee',
    uniSwap: 'Uni Swap',
    panCakeSwap: 'Pancake Swap',
    transactionDetails: 'Transaction Details',
    transactionOn: 'Transaction on:',
    transactionDate: 'Transaction Date:',
    viewInTransactionExplorer: 'View in browser explorer',
    yes: 'Yes',
    Epay: 'E Pay',
    pleaseEnterAmount: 'Please enter amount',
    invalidamount: 'Invalid Amount',
    liquidityOption: 'Add\nLiquidity',
    liquidityTitle: 'Add Liquidity',
    selectcrypto: 'Select crypto',
    liquidity: 'Liquidity',
    fetching_prices_please_wait: 'Fetching prices please wait',
    chooselanguage: 'Language',//Change (Remove Choose)
    dontshare: '*** Dont share seed phrase ***',
    selectLangProceed: 'Select your preferable language to proceed',
    enterSixDigitPin: 'Enter the 6 Digit Pin to access the wallet',
    reEnterSixDigitPin: 'Re-Enter the 6 digit Pin to access the wallet',
    easeToUse: 'Ease to use & Highly Secure',//Change
    allTxMultCrpt: 'Allow transactions across multiple crypto currencies',
    importYourWallet: 'Import your wallet',
    createNewWallet: 'Create New Wallet',
    namingYourWallet:
      'Naming your wallet will help you track your multiple wallets easily.',
    nameYourWallet: 'Name your wallet',
    VerifyPhrase: 'Verify Phrase',
    enterMnemonoics: 'Enter Mnemonics',
    enterPhrase: 'Enter Phrase',
    Bulk: 'Bulk',
    resetAPin: 'Reset PIN',
    enterPinAccessWallet: 'Enter the 6 Digit PIN to access the wallet',
    profileSettings: 'Settings',
    price: 'Price',
    youCantProceed: 'You cannot proceed',
    rootedDevice: 'Your device is rooted. You cannot proceed.',
    WalletConnect: 'Wallet Connect',
    ScanQRCode: 'Scan QR-Code',
    secretPhrases: 'Secret Phrases',//New
    useCryptoEasier: 'Using your crypto just got easier',//New
    limitlessWorld: 'in a limitless world of credit cards',//New
    getStarted: "Get Started",//New
    saitaPro: "SaitaPro",//New
    fangArt: 'FANG Art',//New
    saitamaStore: 'Saitama Store',//New
    saitaMarket: 'SaitaMarket',//New
    learn: 'Learn',//New
    getSupport: 'Get Support',//New
    uploadCSVFile: 'Upload CSV File',//New
    tokenName: 'Token Name',//New
    trade:'Trade',//New
  },
  Español: {
    cardsetting: 'Card Settings',
    cardpassword: 'Change Password',
    cardlogout: 'Logout',
    forgot: 'Forgot Password',
    newpassword: 'New Password',
    enternewpassword: 'New Password',
    confirmpassword: 'Confirm Password',

    applyCard: 'Apply for the card',
    SaitamaInu: 'Saitama',
    Bulk: 'Bulk',
    nameYourWallet: 'Name your wallet',
    shortBy: 'Short by',
    selectcrypto: 'Select crypto',
    liquidity: 'Liquidity',
    Epay: 'E Pay',
    invalidamount: 'Invalid Amount',
    liquidityOption: 'Add\nLiquidity',
    liquidityTitle: 'Add Liquidity',
    yes: 'Yes',
    princeImpact: 'Impacto no Preço',
    sortBy: 'Ordenar por',
    attachScreenshotsRequired: 'Please Attach Screenshots',
    transactionLinkRequired: 'Transaction link is required',
    multiSend: 'Bulk\nTransfer',
    enterCorrectPin: 'Please enter the correct PIN',
    lets: "Let's get started",
    enterCorrectPin: 'Por favor ingrese el PIN correcto',

    withdrawalAddress: 'Dirección de retiro',
    MultiWallet: 'Administrar billetera',
    from: 'De',
    updateWalletName: 'Actualizar',
    addLiquidReceiveLp: 'Agregue liquidez para recibir tokens LP',
    yourLiquid: 'tu liquidez',
    transactions: 'Transactions',
    noCoinEnabled: 'No hay monedas habilitadas',

    enterValue: 'Introducir valor',
    faceIdTouchOId: 'ID de rostro / ID táctil',
    resetYourPin: 'Restablecer su PIN',
    congratulationsForCreateWallet: 'Your wallet is ready.',//Change
    walletCreatedSuccessfully: 'You have successfully created the wallet',
    decimal: 'Decimals',
    symbol: 'Símbolo',
    contractAddress: 'Dirección del contrato',
    enterContractAdress: 'Ingrese la dirección del contrato',
    selectNetwork: 'Select Network',
    seeLess: 'See Less',

    slippageTolerance: 'Slippage tolerance',
    transactionTimeout: 'Transaction Timeout',
    recoveryPhrase: 'Recovery Phrase',
    backupWallet: 'Backup Wallet',
    assets: 'Assets',
    continue: 'Continue',
    search: 'Search',
    ResetCreatePIN: 'Reset Create Pin',
    shareAddress: 'Share Address',
    withDrawlAddress: 'Withdrawal Address',

    pricesAndPool: 'Prices and Pool Share',
    approveCoin: 'Approve ETH',

    stake: 'Stake',
    getYourStaking: 'Get Your Staking',
    duration: 'Duration',
    days: 'Days',
    lockedAmount: 'Locked Amount',
    max: 'Max',
    apy: 'APY',
    lockInPeriod: 'Lock in Period',
    finalRewards: 'Final Rewards',
    enterAmount: 'Enter Amount',
    myEarnings: 'Saitama Balance',
    Rewards: 'Rewards',
    term: 'Term',
    action: 'Action',
    claimed: 'Claimed',
    unStake: 'Unstake',
    daysLeft: 'Days Left',
    receive: 'Receive',

    backupOptions: 'Backup Options',
    exportPublicKeys: 'Export Public Keys',
    wallets: 'Wallets',

    addNewWallet: 'Add New Wallet',
    To: 'To',
    selectToken: 'Select Token',
    removeLiquidity: 'Remove Liquidity',
    remove: 'Remove',
    seeAll: 'See All',
    upLoadCsv: 'Upload CSV FILE',
    bulkTransfer: 'Bulk Transfer',
    buyBtc: 'Buy BTC',
    listOfRecipients: 'List of Recipients',
    defi: 'DeFi',
    account: 'Account',
    theme: 'Theme',
    mode: 'Mode',
    getSupported: 'Get Supported',
    saitaProSupport: 'SaitaPro Support',
    connectWithUs: 'Connect With Us',
    instagram: 'Instagram',
    facebook: 'Facebook',
    twitter: 'Twitter',
    Telegram: 'Telegram',
    discord: 'Discord',
    title1: 'Crear',
    title2: 'Pin',
    UNIQUEPIN: 'PIN ⁄NICO',
    Touchid: 'Touch ID',
    Faceid: 'Face ID',
    Biometrics: 'BiometrÌa',
    Back: 'Atr·s',
    submit: 'Enviar',
    Approved: 'Aprobado',
    EnterPin: 'Introducir Pin',
    ConfirmPin: 'Confirmar Pin',
    CreatingPin: 'Crear PIN',
    CreatePin: 'Create a PIN',

    PinReq: 'Se requerir· este pin de 6 dÌgitos para acceder a la billetera',
    ImportWallet: ')IMPORTAR\nBILLETERA',
    CreateWallet: 'CREAR\nBILLETERA',
    needHelp: 'øNecesitas ayuda para decidirte?',
    walletText:
      'En SaitaPro, puedes crear una billetera no custodiada o importar una existente utilizando tu frase de seguridad.',
    Import: 'Importar',
    Wallet: 'Billetera',
    pasteText:
      'Pega o escribe tu frase de seguridad en el orden correcto separando las palabras con un espacio',
    name: 'Nombre',
    NameWallet: 'Introduce un nombre para tu billetera',
    myWallet: 'My Wallet',//Change
    selectColor: 'Elige un color',
    getStart: 'Empecemos',
    secure: 'Seguro',
    next: 'Siguiente',
    takeNote:
      'Toma nota de tu frase secreta y gu·rdela en un lugar seguro, si pierdes esta frase es posible que no puedas acceder a tu billetera.',
    copyPhrase: 'Copiar frase',
    verify: 'Verificar',
    phrase: 'Frase',
    correctOrder:
      'Haz clic en las palabras en el mismo orden de tu frase de seguridad que se ha mostrado en la pantalla anterior.',
    swap: 'Swap',
    get: 'Recibir',
    send: 'Enviar',
    buy: 'Comprar',
    staking: 'Staking',
    noCoinFound: 'No se encontrÛ ninguna moneda',
    Hot: 'Hot',
    Gainer: 'Gainer',
    Loser: 'Loser',
    Vol: '24h Volume',
    Coin: 'Moneda',
    LastPrice: '⁄ltimo Precio',
    HrChange: '24h Change',
    noGraphFound: 'No se encontrÛ ning˙n gr·fico',
    Home: 'INICIO',
    Market: 'MERCADO',
    Wallet_: 'BILLETERA',
    Settings: 'AJUSTES',
    searchToken: 'Buscar token',
    searchUrl: 'Busque o ingrese la URL del sitio web',
    Finance: 'Finanzas',
    Exchanges: 'Exchanges',
    Games: 'Games',
    NFTs: 'NFTs',
    ok: 'Ok',
    Tokens: 'Tokens',
    Manage: 'Administrar',
    Security: 'Seguridad',
    History: 'Historial',
    Preferences: 'Preferencias',
    BackupOption: 'OpciÛn de copia de seguridad',
    contactUs: 'Cont·ctanos',
    Logout: 'Cerrar sesiÛn',
    Notifications: 'Notificaciones',
    NoNoti: 'Deshabilitar notificaciones',
    select: 'Seleccionar',
    searchBlock: 'Buscar Blockchain',
    NoHistory: '°Ninguna transacciÛn encontrada!',
    addNewContact: 'AÒadir nuevo contacto',
    nameYourContact: 'Nombre de tu contacto',
    enterNameHere: 'Introduce nombre aquÌ',
    addWalletAddress: 'Agregar direcciÛn de billetera',
    address: 'DirecciÛn',
    paste: 'Pegar',
    saveContact: 'Guardar Contacto',
    addToken: 'Agregar Token',
    tokenSymbol: 'SÌmbolo Token',
    ethereum: 'Ethereum',
    binance: 'Binance',
    tokenContactAddress: 'DirecciÛn de contrato de token',
    enterTokenContactAddress: 'Ingrese la direcciÛn del contrato de token',
    tokenSymbol: 'SÌmbolo del Token',
    enterTokenSymbol: 'Introduce el sÌmbolo del token',
    backUpOptions: 'Opciones de copia de seguridad',
    showRecoveryPhrase: 'Mostrar frase de recuperaciÛn',
    exportPrivateKeys: 'Exportar claves privadas',
    changePasscode: 'Cambiar contraseÒa',
    enterSixDigitPin: 'Ingresa el PIN de 6 dÌgitos',
    reEnterSixDigitPin:
      'Vuelva a ingresar el PIN de 6 dígitos para acceder a la billetera',

    history: 'Historial',
    noTransactionFound: '°No se encontrÛ ninguna transacciÛn!',
    confirm: 'Confirmar',
    pin: 'Pin',
    proceed: 'Continuar',
    pinIsRequired: 'Este pin de 6 dÌgitos ser· requerido',
    toAccessWallet: 'para acceder a la billetera',
    transactionFees: 'Tasas de transacciÛn',
    advancedOptions: 'Opciones avanzadas',
    slow: 'Lenta',
    average: 'Promedio',
    fast: 'R·pida',
    totalAmount: 'Cantidad total',
    currencyPreference: 'Preferencia de moneda',
    contactEditedSuccessfully: 'Contacto editado con Èxito',
    errorWhileEditingContact: 'Error al editar contacto',
    editContact: 'Editar contacto',
    enterNameHere: 'Introduce el nombre aquÌ',
    nameYourContact: 'Nombre de tu contacto',
    addWalletAddress: 'Agregar direcciÛn de billetera',
    nameFieldIsRequired: 'El campo "nombre" es obligatorio',
    emailFieldIsRequired: 'El campo "correo electrÛnico" es obligatorio',
    invalidEmail: 'El correo electrÛnico ingresado no es v·lido',
    subjectFieldIsRequired: 'El campo "asunto" es obligatorio',
    messageFieldIsRequired: 'El campo ∑mensaje" es obligatorio',
    addressFieldIsRequired: 'El campo "direcciÛn" es obligatorio',
    invalidAddress: 'DirecciÛn inv·lida',
    requestSentSuccessfully: 'Solicitud enviada con Èxito',
    errorWhileSendingRequest: 'Error al enviar solicitud',
    getInTouch: 'Cont·ctanos',
    forSupport: 'para soporte',
    supportLine: 'This is the official SaitaPro support channel please fill all the fields and provide links and screenshots when applicable, we will contact you shortly through emails',
    // supportLine1: 'Este es el canal de soporte oficial de SaitaPro.',
    supportLine2: 'Por favor completa todos los campos y proporciona enlaces y',
    supportLine3:
      'capturas de pantalla cuando corresponda, nos pondremos en contacto',
    supportLine4: 'contigo en breve a travÈs de correo electrÛnico',
    email: 'E-mail',
    subject: 'Asunto',
    message: 'Mensaje',
    walletAddress: 'DirecciÛn billetera',
    transactionLinks: 'Links de transacciones',
    attachScreenshots: 'Adjuntar capturas de pantalla',
    takePhoto: 'Hacer foto',
    chooseFromGallery: 'Elegir de la galerÌa',
    cancel: 'Cancelar',
    done: 'Hecho',
    setAmount: 'Indicar cantidad',
    copy: 'Copiar',
    share: 'Compartir',
    publicAddress: 'DirecciÛn p˙blica',
    copyPhrase: 'Copiar frase',
    recoveryPhraseText:
      'Toma nota de tu frase secreta y gu·rdala en un lugar seguro, si pierdes esta frase es posible que no puedas acceder a tu billetera.',
    toAccessTheWallet: 'para acceder a la billetera',
    enterPin: 'Introducir Pin',
    enterNewPin: 'Introducir Nuevo Pin',
    creatingAPin: 'Creando un PIN',
    cameraAppPermission: 'Permiso de acceso a la aplicaciÛn c·mara',
    needAccessToCamera: 'SaitaPro App necesita acceso a tu c·mara',
    cameraPermissionDenied: 'Permiso de C¡MARA denegado',
    applock: 'Seguridad',
    searchCurrency: 'Buscar moneda',
    wrongPin: 'Pin ErrÛneo',
    lowBalanceAlert: 'Saldo demasiado bajo para enviar',
    cameraPermissionError: 'Error de permiso de c·mara',
    longPressToPaste: 'PulsaciÛn larga para pegar',
    contacts: 'Contactos',
    amount: 'Cantidad',
    available: 'Disponible',
    transactionFeesBNB: 'Tasas de transacciÛn (BNB)',
    reset: 'Reiniciar',
    gasPrice: 'Precio Gas',
    pleaseEnterGasPrice: 'Por favor indica el precio del gas',
    confirmTransaction: 'Confirmar transacciÛn',
    selectCryptoContact:
      'Seleccione el destinatario a continuaciÛn o agregue uno nuevo para enviar criptoactivos.',
    areYouSure: 'øEst·s seguro?',
    errorWhileDeletingContact: 'Error al eliminar contacto',
    contactDeletedSuccessfully: 'Contacto eliminado con Èxito',
    addNew: 'Agregar nuevo',
    sendCrypto: 'Address Book',
    gasLimit: 'LÌmite de Gas',
    pleaseEnterGasLimit: 'Por favor indica lÌmite de Gas',
    maxPriorityFeeGwei: 'Tasa de prioridad m·xima (Gwei)',
    enterMaxPriorityFee: 'Indica la tasa de prioridad m·xima',
    maxFeeGwei: 'Tasa M·xima (Gwei)',
    maxFee: 'Tasa M·xima',
    stakingPools: 'Staking Pools',
    stakedOnly: 'Only Staked',
    live: 'Live',
    finished: 'Finalizados',
    sortBy: 'Ordenar por',
    openSoon: 'Abrir· Pronto',
    hot: 'Hot',
    totalStaked: 'Total staked',
    youSend: 'Tu envÌas',
    btc: 'BTC',
    youReceive: 'Tu recibes (valor aprox.)',
    rate: 'Rate',
    inverseRate: 'Inverse Rate',
    priceImpact: 'Impacto en el Precio',
    gwei: 'Gwei',
    estimateGasFee: 'Tasa de Gas Estimada',
    liquidityFee: 'Tasa de liquidez',
    uniSwap: 'UniSwap',
    panCakeSwap: 'PancakeSwap',
    transactionDetails: 'Detalles de transacciÛn',
    transactionOn: 'TransacciÛn en:',
    viewInTransactionExplorer: 'ver en el explorador de navegaciÛn',
    chooselanguage: 'Elige lengua',
    dontshare: '*** No compartas la frase inicial ***',
    receive: 'Receive',
    selectLangProceed: 'Select your preferable language to proceed',
    easeToUse: 'Ease to use & highly secure',
    allTxMultCrpt: 'Allow transactions across multiple crypto currencies',
    importYourWallet: 'Import New Wallet',
    createNewWallet: 'Create New Wallet',
    namingYourWallet:
      'Naming your wallet will help you track your multiple wallets easily.',
    VerifyPhrase: 'Verify Phrase',
    enterMnemonoics: 'Enter Mnemonics',
    enterPhrase: 'Enter Phrase',
    addCustomToken: 'Add Custom Token',
    resetAPin: 'Reset PIN',
    enterPinAccessWallet: 'Enter the 6 Digit PIN to access the wallet',
    profileSettings: 'Settings',
    price: 'Price',
    WalletConnect: 'Wallet Connect',
    ScanQRCode: 'Escanear código QR',
    secretPhrases: 'Secret Phrases',
    useCryptoEasier: 'Using your crypto just got easier',//New
    limitlessWorld: 'in a limitless world of credit cards',
    getStarted: "Get Started",
    saitaPro: "SaitaPro",
    fangArt: 'FANG Art',
    saitamaStore: 'Saitama Store',
    saitaMarket: 'SaitaMarket',
    learn: 'Learn',
    getSupport: 'Get Support',
    uploadCSVFile: 'Upload CSV File',
    tokenName: 'Token Name',
    trade:'Trade',
  },
  Deutsch: {
    cardsetting: 'Card Settings',
    cardpassword: 'Change Password',
    cardlogout: 'Logout',
    forgot: 'Forgot Password',
    newpassword: 'New Password',
    enternewpassword: 'New Password',
    confirmpassword: 'Confirm Password',

    applyCard: 'Apply for the card',
    Import: 'Import',
    price: 'Price',
    shortBy: 'Short by',
    SaitamaInu: 'Saitama',
    Home: 'INICIO',
    Market: 'MERCADO',
    Wallet_: 'CARTEIRA',
    selectcrypto: 'Select crypto',
    liquidity: 'Liquidity',
    Epay: 'E Pay',
    invalidamount: 'Invalid Amount',
    liquidityOption: 'Add\nLiquidity',
    liquidityTitle: 'Add Liquidity',
    yes: 'Yes',
    princeImpact: 'Impacto no Preço',
    sortBy: 'Ordenar por',
    attachScreenshotsRequired: 'Please Attach Screenshots',

    transactionLinkRequired: 'Transaction link is required',
    multiSend: 'Bulk\nTransfer',
    lets: "Let's get started",
    reEnterSixDigitPin:
      'Vuelva a ingresar el PIN de 6 digitos para toegang tot de portemonnee',

    ConfirmPin: 'Bevestigingspin',
    enterCorrectPin: 'Please enter the correct PIN',
    MultiWallet: 'Portemonnee beheren',
    withdrawalAddress: 'Withdrawal Address',

    updateWalletName: 'Update',
    addLiquidReceiveLp: 'Add liquidity to receive LP tokens',
    yourLiquid: 'Your liquidity',
    addLiquidReceiveLp: 'Add liquidity to receive LP tokens',
    yourLiquid: 'Your liquidity',
    from: 'From',

    transactions: 'Transactions',
    noCoinEnabled: 'No Coins Enabled',

    enterValue: 'Enter value',
    faceIdTouchOId: 'Face ID / Touch Id',
    resetYourPin: 'Reset your PIN',
    congratulationsForCreateWallet: 'Your wallet is ready.',//Change
    walletCreatedSuccessfully: 'You have successfully created the wallet',
    decimal: 'Decimals',
    symbol: 'Symbol',
    contractAddress: 'Contract Address',
    enterContractAdress: 'Enter Contract Address',
    selectNetwork: 'Select Network',
    seeLess: 'See Less',

    slippageTolerance: 'Slippage tolerance',
    transactionTimeout: 'Transaction Timeout',
    recoveryPhrase: 'Recovery Phrase',
    backupWallet: 'Backup Wallet',
    assets: 'Assets',
    continue: 'Continue',
    search: 'Search',
    ResetCreatePIN: 'Reset Create Pin',
    shareAddress: 'Share Address',
    withDrawlAddress: 'Withdrawal Address',

    pricesAndPool: 'Prices and Pool Share',
    approveCoin: 'Approve ETH',
    stake: 'Stake',
    getYourStaking: 'Get Your Staking',
    duration: 'Duration',
    days: 'Days',
    lockedAmount: 'Locked Amount',
    max: 'Max',
    apy: 'APY',
    lockInPeriod: 'Lock in Period',
    finalRewards: 'Final Rewards',
    enterAmount: 'Enter Amount',
    myEarnings: 'Saitama Balance',
    Rewards: 'Rewards',
    term: 'Term',
    action: 'Action',
    claimed: 'Claimed',
    unStake: 'Unstake',
    daysLeft: 'Days Left',
    receive: 'Receive',

    backupOptions: 'Backup Options',
    exportPublicKeys: 'Export Public Keys',
    wallets: 'Wallets',

    addNewWallet: 'Add New Wallet',
    To: 'To',
    chooselanguage: 'Kies een taal',
    seeAll: 'See All',
    upLoadCsv: 'Upload CSV FILE',
    bulkTransfer: 'Bulk Transfer',
    selectToken: 'Select Token',
    removeLiquidity: 'Remove Liquidity',
    remove: 'Remove',
    buyBtc: 'Buy BTC',
    listOfRecipients: 'List of Recipients',
    defi: 'DeFi',
    account: 'Account',
    theme: 'Theme',
    mode: 'Mode',
    getSupported: 'Get Supported',
    saitaProSupport: 'SaitaPro Support',
    connectWithUs: 'Connect With Us',
    instagram: 'Instagram',
    facebook: 'Facebook',
    twitter: 'Twitter',
    Telegram: 'Telegram',
    discord: 'Discord',
    profileSettings: 'Settings',
    nameYourWallet: 'Geef je portemonnee een naam',
    Bulk: 'Bulk',
    selectLangProceed: 'Select your preferable language to proceed',
    easeToUse: 'Ease to use & highly secure',
    allTxMultCrpt: 'Allow transactions across multiple crypto currencies',
    importYourWallet: 'Importeer je portemonnee',
    createNewWallet: 'Nieuwe portemonnee maken',
    namingYourWallet:
      'Naming your wallet will help you track your multiple wallets easily.',
    VerifyPhrase: 'Verifieer zin',
    enterMnemonoics: 'Enter Mnemonics',
    enterPhrase: 'Enter Phrase',

    addCustomToken: 'Add Custom Token',
    resetAPin: 'Reset PIN',
    enterPinAccessWallet: 'Enter the 6 Digit PIN to access the wallet',

    CreatePin: {
      title1: 'Stecknadel',
      title2: 'erstellen',
      CreatePin: 'Create a PIN',

      UNIQUEPIN: 'EINZIGARTIGE PIN',
      EnterPin: 'Enter PIN',
      Touchid: 'Berührungsidentifikation',
      Faceid: 'Gesichts-ID',
      Biometrics: 'Biometrie',
      Back: 'Der Rücken',
      Approved: 'Genehmigt',
    },
    WalletConnect: 'Wallet Connect',
    ScanQRCode: 'Scan QR-code',
    secretPhrases: 'Secret Phrases',
    useCryptoEasier: 'Using your crypto just got easier',//New
    limitlessWorld: 'in a limitless world of credit cards',
    getStarted: "Get Started",
    saitaPro: "SaitaPro",
    fangArt: 'FANG Art',
    saitamaStore: 'Saitama Store',
    saitaMarket: 'SaitaMarket',
    learn: 'Learn',
    getSupport: 'Get Support',
    uploadCSVFile: 'Upload CSV File',
    tokenName: 'Token Name',
    trade:'Trade',
  },

  Français: {
    cardsetting: 'Card Settings',
    cardpassword: 'Change Password',
    cardlogout: 'Logout',
    forgot: 'Forgot Password',
    newpassword: 'New Password',
    enternewpassword: 'New Password',
    confirmpassword: 'Confirm Password',
    applyCard: 'Apply for the card',
    SaitamaInu: 'Saitama',
    shortBy: 'Short by',
    selectcrypto: 'Select crypto',
    liquidity: 'Liquidity',
    Epay: 'E Pay',
    invalidamount: 'Invalid Amount',
    liquidityOption: 'Add\nLiquidity',
    liquidityTitle: 'Add Liquidity',
    yes: 'Yes',
    princeImpact: 'Impacto no Preço',
    sortBy: 'Ordenar por',
    attachScreenshotsRequired: 'Please Attach Screenshots',
    transactionLinkRequired: 'Transaction link is required',
    multiSend: 'Bulk\nTransfer',
    lets: "Let's get started",
    enterCorrectPin: 'Please enter the correct PIN',
    MultiWallet: 'Gérer le portefeuille',
    withdrawalAddress: 'Withdrawal Address',

    updateWalletName: 'Update',
    addLiquidReceiveLp: 'Add liquidity to receive LP tokens',
    yourLiquid: 'Your liquidity',
    transactions: 'Transactions',
    noCoinEnabled: 'No Coins Enabled',

    from: 'From',

    enterValue: 'Enter value',
    faceIdTouchOId: 'Face ID / Touch Id',
    resetYourPin: 'Reset your PIN',
    congratulationsForCreateWallet: 'Your wallet is ready.',//Change
    walletCreatedSuccessfully: 'You have successfully created the wallet',
    decimal: 'Decimals',
    symbol: 'Symbol',
    contractAddress: 'Contract Address',
    enterContractAdress: 'Enter Contract Address',
    selectNetwork: 'Select Network',
    seeLess: 'See Less',

    slippageTolerance: 'Slippage tolerance',
    transactionTimeout: 'Transaction Timeout',
    recoveryPhrase: 'Recovery Phrase',
    backupWallet: 'Backup Wallet',
    assets: 'Assets',
    continue: 'Continue',
    search: 'Search',
    ResetCreatePIN: 'Reset Create Pin',
    shareAddress: 'Share Address',
    withDrawlAddress: 'Withdrawal Address',

    search: 'Search',
    continue: 'Continue',
    pricesAndPool: 'Prices and Pool Share',
    approveCoin: 'Approve ETH',
    stake: 'Stake',
    getYourStaking: 'Get Your Staking',
    duration: 'Duration',
    days: 'Days',
    lockedAmount: 'Locked Amount',
    max: 'Max',
    apy: 'APY',
    lockInPeriod: 'Lock in Period',
    finalRewards: 'Final Rewards',
    enterAmount: 'Enter Amount',
    myEarnings: 'Saitama Balance',
    Rewards: 'Rewards',
    term: 'Term',
    action: 'Action',
    claimed: 'Claimed',
    unStake: 'Unstake',
    daysLeft: 'Days Left',
    receive: 'Receive',

    backupOptions: 'Backup Options',
    exportPublicKeys: 'Export Public Keys',
    wallets: 'Wallets',

    addNewWallet: 'Add New Wallet',
    To: 'To',

    seeAll: 'See All',
    buyBtc: 'Buy BTC',
    listOfRecipients: 'List of Recipients',
    upLoadCsv: 'Upload CSV FILE',
    bulkTransfer: 'Bulk Transfer',
    selectToken: 'Select Token',
    removeLiquidity: 'Remove Liquidity',
    remove: 'Remove',
    defi: 'DeFi',
    account: 'Account',
    theme: 'Theme',
    mode: 'Mode',
    getSupported: 'Get Supported',
    saitaProSupport: 'SaitaPro Support',
    connectWithUs: 'Connect With Us',
    instagram: 'Instagram',
    facebook: 'Facebook',
    twitter: 'Twitter',
    Telegram: 'Telegram',
    discord: 'Discord',
    title1: 'Créer',
    title2: 'Code PIN',
    UNIQUEPIN: 'Code PIN Unique',
    Touchid: 'Touch ID',
    Faceid: 'Face ID',
    Biometrics: 'Biométrique',
    Back: 'Retour',
    submit: 'Soumettre',
    Approved: 'Approuvé',
    EnterPin: 'Entrer le code PIN',
    ConfirmPin: 'Confirmer le code PIN',
    CreatingPin: 'Créer un code PIN',
    CreatePin: 'Create a PIN',
    PinReq:
      'Ce code PIN à 6 chiffres vous sera demandé afin d’accéder à votre portefeuille',
    ImportWallet: 'Importer un portefeuille',
    CreateWallet: 'Créer un portefeuille',
    needHelp: 'Besoin de conseils pour vous décider ?',
    walletText:
      'Sur Saitapro, vous pouvez créer un portefeuille non custodial ou en importer un déjà existant à l’aide de votre phrase de sécurité.',
    Import: 'Importer',
    Wallet: 'Portefeuille',
    pasteText:
      'Coller ou écrivez votre phrase de sécurité dans le bon ordre, avec un espace entre chaque mot.',
    name: 'Nom',
    NameWallet: 'Entrer un nom pour votre portefeuille',
    myWallet: 'My Wallet',//Change
    selectColor: 'Sélectionnez une couleur',
    getStart: ' C’est parti !',
    secure: 'Sécuriser',
    next: 'Suivant',
    takeNote:
      'Écrivez votre phrase de sécurité sur un papier et gardez-là en lieu sûr. Si vous la perdrez vous ne serez plus en mesure d’accéder à votre portefeuille.',
    copyPhrase: 'Copier la phrase',
    verify: 'Vérifier',
    phrase: 'Phrase',
    correctOrder:
      'Cliquez sur les mots de votre phrase de sécurité dans le même ordre que sur l’écran précédent.',
    swap: 'Échanger',
    get: 'Recevoir',
    send: 'Envoyer',
    buy: 'Acheter',
    staking: 'Staking',
    noCoinFound: ' Pièce non trouvée',
    Hot: 'Hot',
    Gainer: 'Gagnant',
    Loser: 'Perdant',
    Vol: '24h Volume',
    Coin: 'Pièce',
    LastPrice: 'Dernier Prix',
    HrChange: 'Échange sur 24h',
    noGraphFound: 'Graphique non trouvé',
    Saitama: 'Saitama',
    Home: 'ACCUEIL',
    Market: 'MARCHÉ',
    Wallet_: 'PORTEFEUILLE',
    Settings: 'RÉGAGLES',
    searchToken: 'Rechercher un token',
    searchUrl: ' Rechercher ou entrer l’URL d’un site web ',
    Finance: 'Finance',
    Exchanges: 'Plateformes d’Échanges',
    Games: 'Jeux',
    NFTs: 'NFTs',
    ok: 'Ok',
    Tokens: 'Tokens',
    Manage: 'Gérer',
    Security: 'Sécurité',
    History: 'Historique',
    Preferences: 'Préférences',
    BackupOption: 'Options de sauvegarde',
    contactUs: 'Contactez-nous',
    Logout: 'Se déconnecter',
    Notifications: 'Notifications',
    NoNoti: 'Pas de notifications',
    select: 'Sélectionner',
    searchBlock: 'Rechercher une blockchain',
    NoHistory: 'Pas de transactions trouvée !',
    addNewContact: 'Ajouter un nouveau Contact',
    nameYourContact: 'Nommer votre Contact',
    enterNameHere: ' Entrer le nom ici',
    addWalletAddress: 'Ajouter une adresse de portefeuille',
    address: 'Addresse',
    paste: 'Coller',
    saveContact: 'Sauvegarder le Contact',
    addToken: 'Ajouter Token',
    tokenSymbol: 'Symbole du Tokenl',
    ethereum: 'Ethereum',
    binance: 'Binance',
    tokenContactAddress: 'Adresse du contrat du Token',
    enterTokenContactAddress: 'Entrer l’adresse du contrat du Token',
    tokenSymbol: 'Symbole du Token',
    enterTokenSymbol: 'Enter Token Symbol',
    backUpOptions: 'Backup Options',
    showRecoveryPhrase: 'Show Recovery Phrase',
    exportPrivateKeys: 'Export Private Keys',
    changePasscode: 'Change PassCode',
    enterSixDigitPin: 'Entrer un code PIN à 6 Chiffres',
    reEnterSixDigitPin:
      'Entrez à nouveau le code PIN à 6 chiffres pour accéder au portefeuille',

    history: 'Historique',
    noTransactionFound: 'Pas de transactions trouvées!',
    confirm: 'Confirmer',
    pin: 'PIN',
    proceed: 'Continuer',
    pinIsRequired: 'Votre code PIN à 6 chiffres vous sera demandé',
    toAccessWallet: 'pour accéder au portefeuile',
    transactionFees: 'Frais de transactions',
    advancedOptions: 'Options avancées',
    slow: 'Lent',
    average: 'Normal',
    fast: 'Rapide',
    totalAmount: 'Montant Total',
    currencyPreference: 'Préférences des cryptomonnaies',
    contactEditedSuccessfully: 'Le contact a bien été modifié',
    errorWhileEditingContact: 'Erreur durant la moditfication du contact',
    editContact: 'Éditer un contact',
    enterNameHere: 'Entrer le nom ici',
    nameYourContact: 'Nommez votre Contact',
    addWalletAddress: 'Ajouter l’adresse du portefeuille',
    nameFieldIsRequired: 'Le champ “Nom” est requis',
    emailFieldIsRequired: ' Le champ “E-mail” est requis',
    invalidEmail: 'L’E-mail entré est invalide',
    subjectFieldIsRequired: 'Le champ “Sujet” est requis',
    messageFieldIsRequired: 'Le champ “Message” est requis',
    addressFieldIsRequired: 'Le champ “Adresse” est requis',
    invalidAddress: 'Adresse invalide',
    requestSentSuccessfully: 'Requête envoyée avec succès',
    errorWhileSendingRequest: 'Erreur durant l’envoi de la requête',
    getInTouch: 'Rester en contact',
    forSupport: 'Pour de l’assistance',
    supportLine: 'This is the official SaitaPro support channel please fill all the fields and provide links and screenshots when applicable, we will contact you shortly through emails',
    // supportLine1: 'Bienvenue sur l’assistance officielle de Saitapro',
    supportLine2:
      'Veuillez remplir tous les champs et fournir tous les liens et',
    supportLine3: 'captures d’écrans nécessaires. Nous vous contacterons',
    supportLine4: 'dès que possible via E-Mail',
    email: 'E-mail',
    subject: 'Sujet',
    message: 'Message',
    walletAddress: 'Adresse du portefeuille',
    transactionLinks: ' Lien de la transaction',
    attachScreenshots: 'Joindre une capture d’écran',
    takePhoto: 'Prendre une photo',
    chooseFromGallery: 'Sélectionner dans la galerie',
    cancel: 'Annuler',
    done: 'Terminé',
    setAmount: 'Définir un montant',
    copy: 'Copier',
    share: 'Partager',
    publicAddress: ' Adresse publique',
    copyPhrase: 'Copier la phrase',
    recoveryPhraseText:
      'Écrivez votre phrase de sécurité sur un papier et gardez-là en lieu sûr. Si vous la perdrez vous ne serez pas en mesure d’accéder à votre portefeuille.',
    toAccessTheWallet: 'accéder à votre portefeuille',
    enterPin: 'Entrer le code PIN',
    enterNewPin: ' Entrer le nouveau code PIN',
    creatingAPin: 'Créer un code PIN',
    cameraAppPermission: ' Autorisation d’accéder à l’appareil photo',
    needAccessToCamera: 'Saitapro a besoin d’accéder à votre appareil photo.',
    cameraPermissionDenied:
      'Autorisation d’accèder à l’appareil photo refusée.',
    applock: 'Sécurité',
    searchCurrency: 'Rechercher une cryptomonnaie',
    wrongPin: 'Code PIN faux',
    lowBalanceAlert: 'Balance too low to send',
    cameraPermissionError: 'Erreur Autorisation de l’appareil photo',
    longPressToPaste: 'Appuyer longuement pour coller',
    contacts: 'Contacts',
    amount: 'Montant',
    available: 'Disponible',
    transactionFeesBNB: 'Frais de Transaction (BNB)',
    reset: 'Réinitialiser',
    gasPrice: 'Prix du Gas',
    pleaseEnterGasPrice: 'Veuillez entrer le prix du Gas',
    confirmTransaction: 'Confirmer la transaction',
    selectCryptoContact:
      'Sélectionner le destinataire ci-dessous ou ajouter un nouveau destinataire pour envoyer des crypto-actifs',
    areYouSure: 'Êtes-vous surs ?',
    errorWhileDeletingContact: 'Erreur pendant la suppression du contact',
    contactDeletedSuccessfully: 'Contact supprimé avec succès',
    addNew: ' Ajouter un nouveau contact',
    sendCrypto: 'Address Book',
    gasLimit: 'Limite de Gas',
    pleaseEnterGasLimit: 'Veuillez indiquer une limite de Gas',
    maxPriorityFeeGwei: 'Priorité Maximum des frais (GWEI)',
    enterMaxPriorityFee: 'Veuillez indiquer la Priorité Maximum des Frais',
    maxFeeGwei: 'Frais maximum (Gwei)',
    maxFee: 'Frais maximum',
    stakingPools: 'Staking Pools',
    stakedOnly: 'Staked Only',
    live: 'Live',
    finished: 'Terminé',
    sortBy: 'Classé par',
    openSoon: 'Prochainement',
    hot: 'Hot',
    totalStaked: 'Total staked',
    youSend: 'Vous envoyez',
    btc: 'BTC',
    youReceive: 'Vous recevez (Estimation)',
    rate: 'Rate',
    inverseRate: 'Inverse Rate',
    priceImpact: 'Impact du prix',
    gwei: 'Gwei',
    estimateGasFee: 'Estimation des frais de gas',
    liquidityFee: 'Frais de liquidités',
    uniSwap: 'Uni Swap',
    panCakeSwap: 'Pancake Swap',
    transactionDetails: 'Détails de la transaction',
    transactionOn: 'Transaction active:',
    viewInTransactionExplorer: 'Voir la transaction dans l’explorateur',
    chooselanguage: 'Choisissez la langue',
    dontshare: '*** Ne partagez pas la phrase de départ ***',
    selectLangProceed: 'Select your preferable language to proceed',
    easeToUse: 'Ease to use & highly secure',
    allTxMultCrpt: 'Allow transactions across multiple crypto currencies',
    importYourWallet: 'Import your wallet',
    createNewWallet: 'Create New Wallet',
    namingYourWallet:
      'Naming your wallet will help you track your multiple wallets easily.',
    nameYourWallet: 'Name your wallet',
    VerifyPhrase: 'Verify Phrase',
    enterMnemonoics: 'Enter Mnemonics',
    enterPhrase: 'Enter Phrase',
    Bulk: 'Bulk',
    addCustomToken: 'Add Custom Token',
    resetAPin: 'Reset PIN',
    enterPinAccessWallet: 'Enter the 6 Digit PIN to access the wallet',
    profileSettings: 'Settings',
    price: 'Price',
    WalletConnect: 'Wallet Connect',
    ScanQRCode: 'Scannez le code QR',
    secretPhrases: 'Secret Phrases',
    useCryptoEasier: 'Using your crypto just got easier',//New
    limitlessWorld: 'in a limitless world of credit cards',
    getStarted: "Get Started",
    saitaPro: "SaitaPro",
    fangArt: 'FANG Art',
    saitamaStore: 'Saitama Store',
    saitaMarket: 'SaitaMarket',
    learn: 'Learn',
    getSupport: 'Get Support',
    uploadCSVFile: 'Upload CSV File',
    tokenName: 'Token Name',
    trade:'Trade',
  },

  Italian: {
    cardsetting: 'Card Settings',
    cardpassword: 'Change Password',
    cardlogout: 'Logout',
    forgot: 'Forgot Password',
    newpassword: 'New Password',
    enternewpassword: 'New Password',
    confirmpassword: 'Confirm Password',
    applyCard: 'Apply for the card',
    SaitamaInu: 'Saitama',
    shortBy: 'Short by',
    selectcrypto: 'Select crypto',
    liquidity: 'Liquidity',
    Epay: 'E Pay',
    invalidamount: 'Invalid Amount',
    liquidityOption: 'Add\nLiquidity',
    liquidityTitle: 'Add Liquidity',
    yes: 'Yes',
    princeImpact: 'Impacto no Preço',
    sortBy: 'Ordenar por',
    attachScreenshotsRequired: 'Please Attach Screenshots',
    transactionLinkRequired: 'Transaction link is required',
    multiSend: 'Bulk\nTransfer',
    lets: "Let's get started",
    enterCorrectPin: 'Please enter the correct PIN',
    MultiWallet: 'Gestisci portafoglio',
    withdrawalAddress: 'Withdrawal Address',

    updateWalletName: 'Update',
    addLiquidReceiveLp: 'Add liquidity to receive LP tokens',
    yourLiquid: 'Your liquidity',
    transactions: 'Transactions',
    noCoinEnabled: 'No Coins Enabled',
    from: 'From',

    enterValue: 'Enter value',
    faceIdTouchOId: 'Face ID / Touch Id',
    resetYourPin: 'Reset your PIN',
    congratulationsForCreateWallet: 'Your wallet is ready.',//Change
    walletCreatedSuccessfully: 'You have successfully created the wallet',
    decimal: 'Decimals',
    symbol: 'Symbol',
    contractAddress: 'Contract Address',
    enterContractAdress: 'Enter Contract Address',
    selectNetwork: 'Select Network',
    seeLess: 'See Less',

    slippageTolerance: 'Slippage tolerance',
    transactionTimeout: 'Transaction Timeout',
    recoveryPhrase: 'Recovery Phrase',
    backupWallet: 'Backup Wallet',
    assets: 'Assets',
    continue: 'Continue',
    search: 'Search',
    ResetCreatePIN: 'Reset Create Pin',
    shareAddress: 'Share Address',
    withDrawlAddress: 'Withdrawal Address',

    pricesAndPool: 'Prices and Pool Share',
    approveCoin: 'Approve ETH',
    stake: 'Stake',
    getYourStaking: 'Get Your Staking',
    duration: 'Duration',
    days: 'Days',
    lockedAmount: 'Locked Amount',
    max: 'Max',
    apy: 'APY',
    lockInPeriod: 'Lock in Period',
    finalRewards: 'Final Rewards',
    enterAmount: 'Enter Amount',
    myEarnings: 'Saitama Balance',
    Rewards: 'Rewards',
    term: 'Term',
    action: 'Action',
    claimed: 'Claimed',
    unStake: 'Unstake',
    daysLeft: 'Days Left',
    receive: 'Receive',

    backupOptions: 'Backup Options',
    exportPublicKeys: 'Export Public Keys',
    wallets: 'Wallets',

    addNewWallet: 'Add New Wallet',
    To: 'To',

    seeAll: 'See All',
    buyBtc: 'Buy BTC',
    listOfRecipients: 'List of Recipients',
    upLoadCsv: 'Upload CSV FILE',
    bulkTransfer: 'Bulk Transfer',
    selectToken: 'Select Token',
    removeLiquidity: 'Remove Liquidity',
    remove: 'Remove',
    defi: 'DeFi',
    account: 'Account',
    theme: 'Theme',
    mode: 'Mode',
    getSupported: 'Get Supported',
    saitaProSupport: 'SaitaPro Support',
    connectWithUs: 'Connect With Us',
    instagram: 'Instagram',
    facebook: 'Facebook',
    twitter: 'Twitter',
    Telegram: 'Telegram',
    discord: 'Discord',
    profileSettings: 'Settings',
    title1: 'Crea',
    title2: 'Pin',
    UNIQUEPIN: 'Pin Univoco',
    Touchid: 'Touch ID',
    Faceid: 'Face ID',
    Biometrics: 'Dati Biometrici',
    Back: 'Indietro',
    submit: 'Invia',
    Approved: 'Approva',
    EnterPin: 'Inserisci il Pin',
    ConfirmPin: 'Conferma il Pin',
    CreatingPin: 'Crea un PIN',
    CreatePin: 'Create a PIN',
    PinReq: 'Questo pin a 6 cifre sarà richiesto\nper accedere al wallet',
    ImportWallet: 'IMPORTA\nWALLET',
    CreateWallet: 'CREA\nWALLET',
    needHelp: 'Ti serve aiuto per decidere?',
    walletText:
      'Con SaitaPro puoi creare un\nwallet non-custodial o importane uno esistente\n usando la tua frase di sicurezza.',
    Import: 'Importa',
    Wallet: 'Wallet',
    pasteText:
      'Scrivi o incolla la tua frase di sicurezza nell’ordine corretto, dividendo ogni parola con uno spazio',
    name: 'Nome',
    NameWallet: 'Inserisci un nome per il tuo wallet',
    myWallet: 'My Wallet',//Change
    selectColor: 'Seleziona un colore',
    getStart: 'Iniziamo!',
    secure: 'Secure',
    next: 'Avanti',
    takeNote:
      'Conserva la tua frase di sicurezza con attenzione e in un posto sicuro, se la perderai nessuno sarà in grado di aiutarti e non sarai più in grado di accedere al tuo wallet.',
    copyPhrase: 'Copia frase',
    verify: 'Verifica',
    phrase: 'Frase',
    correctOrder:
      'Clicca sulle parole nell’ordine corretto, come mostrato nella schermata precedente.',
    swap: 'Swap',
    get: 'Ricevi',
    send: 'Invia',
    buy: 'Acquista',
    staking: 'Staking',
    noCoinFound: 'Nessuna moneta trovata',
    Hot: 'Hot',
    Gainer: 'In Guadagno',
    Loser: 'In Perdita',
    Vol: '24h Volume',
    Coin: 'Moneta',
    LastPrice: 'Prezzo',
    HrChange: '24 ore chg%',
    noGraphFound: 'Nessun grafico trovato',
    Saitama: 'Saitama',
    Home: 'Home',
    Market: 'MERCATI',
    Wallet_: 'Wallet',
    Settings: 'IMPOSTAZIONI',
    searchToken: 'Cerca token',
    searchUrl: 'Cerca o inserisci un url ',
    Finance: 'Finance',
    Exchanges: 'Exchanges',
    Games: 'Giochi',
    NFTs: 'NFTs',
    ok: 'Ok',
    Tokens: 'Tokens',
    Manage: 'Gestisci',
    Security: 'Sicurezza',
    History: 'Cronologia',
    Preferences: 'Preferenze',
    BackupOption: 'Opzioni di Backup',
    contactUs: 'Ci trovi su',
    Logout: 'Logout',
    Notifications: 'Notifiche',
    NoNoti: 'Nessuna nuova notifica',
    select: 'Seleziona',
    searchBlock: 'Cerca la Blockchain',
    NoHistory: 'Nessuna Transazione Trovata !',
    addNewContact: 'Aggiungi un Nuovo Contatto',
    nameYourContact: 'Nome del Tuo Contatto',
    enterNameHere: 'Inserisci il Nome Qui',
    addWalletAddress: 'Inserisci l’Indirizzo del Wallet',
    address: 'Indirizzo',
    paste: 'Incolla',
    saveContact: 'Salva Contatto',
    addToken: 'Aggiungi Token',
    tokenSymbol: 'Simbolo del Token',
    ethereum: 'Ethereum',
    binance: 'Binance',
    tokenContactAddress: 'Indirizzo del Contratto del Token',
    enterTokenContactAddress: 'Inserisci l’Indirizzo del Contratto del Token',
    tokenSymbol: 'Simbolo del Token',
    enterTokenSymbol: 'Inserisci il Simbolo del Token',
    backUpOptions: 'Opzioni di Backup',
    showRecoveryPhrase: 'Mostra la Frase di Sicurezza',
    exportPrivateKeys: 'Esporta la Chiave Privata',
    changePasscode: 'Cambia il tuo Pin',
    enterSixDigitPin: 'Inserisci il Pin a 6 cifre',
    reEnterSixDigitPin: 'Re-Enter the 6 digit Pin to access the wallet',

    history: 'Cronologia',
    noTransactionFound: 'Nessuna Transazione Trovata !',
    confirm: 'Conferma',
    pin: 'Pin',
    proceed: 'Procedi',
    pinIsRequired: 'Questo pin a 6 cifre sarà richiesto',
    toAccessWallet: 'per accedere al wallet',
    transactionFees: 'Fee della Transazione',
    advancedOptions: 'Opzioni Avanzate',
    slow: 'Lenta',
    average: 'Normale',
    fast: 'Veloce',
    totalAmount: 'Importo Totale',
    currencyPreference: 'Valuta Preferite',
    contactEditedSuccessfully: 'Contatto aggiornato con successo',
    errorWhileEditingContact:
      'E’ apparso un errore durante l’aggiornamento del contatto',
    editContact: 'Modifica Contatto',
    enterNameHere: 'Inserisci Qui il Tuo Contatto',
    nameYourContact: 'Nome del Contatto',
    addWalletAddress: 'Aggiungi l’Indirizzo del Wallet',
    nameFieldIsRequired: 'Il Campo "Nome" è Obbligatorio!',
    emailFieldIsRequired: 'Il Campo "E-Mail" è Obbligatorio! ',
    invalidEmail: 'L’E- Mail Inserita Non è Valida!',
    subjectFieldIsRequired: 'Il Campo "Titolo" è Obbligatorio!',
    messageFieldIsRequired: 'Il Campo "Messaggio" è Obbligatorio!',
    addressFieldIsRequired: 'Il Campo "Indirizzo" è Obbligatorio!',
    invalidAddress: 'Indirizzo Non Valido',
    requestSentSuccessfully: 'Richiesta inviata con successo',
    errorWhileSendingRequest: 'Errore durante l’invio della richiesta',
    getInTouch: 'Contattaci',
    forSupport: 'per assistenza',
    supportLine: 'This is the official SaitaPro support channel please fill all the fields and provide links and screenshots when applicable, we will contact you shortly through emails',
    // supportLine1: 'Questo è il canale ufficiale di SaitaPro',
    supportLine2: 'per favore riempi i campi e forniscici link e/o',
    supportLine3: 'screenshots quando possibile, ti contatteremo',
    supportLine4: 'il prima possibile tramite e-mail',
    email: 'E-mail',
    subject: 'Titolo',
    message: 'Messaggio',
    walletAddress: 'Indirizzo del Wallet',
    transactionLinks: 'Link della Transazione',
    attachScreenshots: 'Allega Screenshots',
    takePhoto: 'Scatta una Foto',
    chooseFromGallery: 'Scegli dalla galleria',
    cancel: 'Annulla',
    done: 'Fatto',
    setAmount: 'Inserisci Importo',
    copy: 'Copia',
    share: 'Condividi',
    publicAddress: 'Indirizzo Pubblico',
    copyPhrase: 'Copia Frase',
    recoveryPhraseText:
      'Conserva la tua frase di sicurezza con attenzione e in un posto sicuro, se la perderai nessuno sarà in grado di aiutarti e non sarai più in grado di accedere al tuo wallet.',
    toAccessTheWallet: 'per accedere al wallet',
    enterPin: 'Inserisci il Pin',
    enterNewPin: 'Inserisci un nuovo Pin',
    creatingAPin: 'Crea un nuovo Pin',
    cameraAppPermission: 'Permessi della fotocamera',
    needAccessToCamera: 'SaitaPro ha bisogno dell’accesso alla tua fotocamera ',
    cameraPermissionDenied: 'Permessi della fotocamera negati',
    applock: 'Sicurezza',
    searchCurrency: 'Cerca Valuta',
    wrongPin: 'Pin Errato !',
    lowBalanceAlert: 'Importo è troppo basso per essere inviato',
    cameraPermissionError: 'Errore permessi fotocamera',
    longPressToPaste: 'Tieni premuto per incollare',
    contacts: 'Contatti',
    amount: 'Importo',
    available: 'Disponibile',
    transactionFeesBNB: 'Tasse di Trasferimento (BNB)',
    reset: 'Reset',
    gasPrice: 'Gas Price',
    pleaseEnterGasPrice: 'Inserire il Gas Price',
    confirmTransaction: 'Conferma la Transazione',
    selectCryptoContact:
      'Seleziona il destinatario di seguito o aggiungi un nuovo destinatario per inviare risorse crittografiche',
    areYouSure: 'Sei sicuro?',
    errorWhileDeletingContact: 'Errore Durante l’Eliminazione del Contatto',
    contactDeletedSuccessfully: 'Contatto Eliminato Correttamente',
    addNew: 'Aggiungi',
    sendCrypto: 'Address Book',
    gasLimit: 'Gas Limit',
    pleaseEnterGasLimit: 'Inserire il Gas Limit',
    maxPriorityFeeGwei: 'Max Priority Fee (Gwei)',
    enterMaxPriorityFee: 'Inserire il Max Priority Fee',
    maxFeeGwei: 'Max Fee (Gwei)',
    maxFee: 'Max Fee',
    stakingPools: 'Staking Pools',
    stakedOnly: 'Staked Only',
    live: 'Live',
    finished: 'Terminato',
    sortBy: 'A breve',
    openSoon: 'Arriverà presto',
    hot: 'Hot',
    totalStaked: 'Total Staked',
    youSend: 'Scambia',
    btc: 'BTC',
    youReceive: 'Riceverai(Stima)',
    rate: 'Tasso di Conversione',
    inverseRate: 'Tasso di Conversione Inverso',
    priceImpact: 'Impatto sul Prezzo',
    gwei: 'Gwei',
    estimateGasFee: 'Gas Fee Previste',
    liquidityFee: 'Liquidity Fee',
    uniSwap: 'UniSwap',
    panCakeSwap: 'PancakeSwap',
    transactionDetails: 'Dettagli della transazione',
    transactionOn: 'Transazione:',
    viewInTransactionExplorer: 'Visualizza nell explorer',
    chooselanguage: 'Scegli la lingua',
    dontshare: '*** Non condividere la frase seme ***',
    selectLangProceed: 'Select your preferable language to proceed',
    easeToUse: 'Ease to use & highly secure',
    allTxMultCrpt: 'Allow transactions across multiple crypto currencies',
    importYourWallet: 'Import your wallet',
    createNewWallet: 'Create New Wallet',
    namingYourWallet:
      'Naming your wallet will help you track your multiple wallets easily.',
    nameYourWallet: 'Name your wallet',
    VerifyPhrase: 'Verify Phrase',
    enterMnemonoics: 'Enter Mnemonics',
    enterPhrase: 'Enter Phrase',
    Bulk: 'Bulk',
    addCustomToken: 'Add Custom Token',
    resetAPin: 'Reset PIN',
    enterPinAccessWallet: 'Enter the 6 Digit PIN to access the wallet',
    price: 'Price',
    WalletConnect: 'Wallet Connect',
    ScanQRCode: 'Scansiona il codice QR',
    secretPhrases: 'Secret Phrases',
    useCryptoEasier: 'Using your crypto just got easier',//New
    limitlessWorld: 'in a limitless world of credit cards',
    getStarted: "Get Started",
    saitaPro: "SaitaPro",
    fangArt: 'FANG Art',
    saitamaStore: 'Saitama Store',
    saitaMarket: 'SaitaMarket',
    learn: 'Learn',
    getSupport: 'Get Support',
    uploadCSVFile: 'Upload CSV File',
    tokenName: 'Token Name',
    trade:'Trade',
  },
  Português: {
    forgot: 'Forgot Password',
    newpassword: 'New Password',
    cardsetting: 'Card Settings',
    cardpassword: 'Change Password',
    cardlogout: 'Logout',
    enternewpassword: 'New Password',
    confirmpassword: 'Confirm Password',

    applyCard: 'Apply for the card',
    Import: 'Import',
    CreatePin: 'Create a PIN',
    shortBy: 'Short by',
    selectcrypto: 'Select crypto',
    liquidity: 'Liquidity',
    Epay: 'E Pay',
    invalidamount: 'Invalid Amount',
    liquidityOption: 'Add\nLiquidity',
    liquidityTitle: 'Add Liquidity',
    yes: 'Yes',
    sortBy: 'Ordenar por',
    attachScreenshotsRequired: 'Please Attach Screenshots',

    transactionLinkRequired: 'Transaction link is required',
    multiSend: 'Bulk\nTransfer',
    lets: "Let's get started",
    enterCorrectPin: 'Please enter the correct PIN',
    MultiWallet: 'Gerenciar carteira',
    withdrawalAddress: 'Withdrawal Address',

    updateWalletName: 'Update',
    addLiquidReceiveLp: 'Add liquidity to receive LP tokens',
    yourLiquid: 'Your liquidity',
    transactions: 'Transactions',
    noCoinEnabled: 'No Coins Enabled',
    from: 'From',

    enterValue: 'Enter value',
    faceIdTouchOId: 'Face ID / Touch Id',
    resetYourPin: 'Reset your PIN',
    congratulationsForCreateWallet: 'Your wallet is ready.',//Change
    walletCreatedSuccessfully: 'You have successfully created the wallet',
    decimal: 'Decimals',
    symbol: 'Symbol',
    contractAddress: 'Contract Address',
    enterContractAdress: 'Enter Contract Address',
    selectNetwork: 'Select Network',
    seeLess: 'See Less',

    slippageTolerance: 'Slippage tolerance',
    transactionTimeout: 'Transaction Timeout',
    recoveryPhrase: 'Recovery Phrase',
    backupWallet: 'Backup Wallet',
    assets: 'Assets',
    continue: 'Continue',
    search: 'Search',
    ResetCreatePIN: 'Reset Create Pin',
    shareAddress: 'Share Address',
    withDrawlAddress: 'Withdrawal Address',

    pricesAndPool: 'Prices and Pool Share',
    approveCoin: 'Approve ETH',
    stake: 'Stake',
    getYourStaking: 'Get Your Staking',
    duration: 'Duration',
    days: 'Days',
    lockedAmount: 'Locked Amount',
    max: 'Max',
    apy: 'APY',
    lockInPeriod: 'Lock in Period',
    finalRewards: 'Final Rewards',
    enterAmount: 'Enter Amount',
    myEarnings: 'Saitama Balance',
    Rewards: 'Rewards',
    term: 'Term',
    action: 'Action',
    claimed: 'Claimed',
    unStake: 'Unstake',
    daysLeft: 'Days Left',
    receive: 'Receive',

    backupOptions: 'Backup Options',
    exportPublicKeys: 'Export Public Keys',
    wallets: 'Wallets',

    addNewWallet: 'Add New Wallet',
    To: 'To',

    seeAll: 'See All',
    buyBtc: 'Buy BTC',
    listOfRecipients: 'List of Recipients',
    upLoadCsv: 'Upload CSV FILE',
    bulkTransfer: 'Bulk Transfer',
    selectToken: 'Select Token',
    removeLiquidity: 'Remove Liquidity',
    remove: 'Remove',
    defi: 'DeFi',
    account: 'Account',
    theme: 'Theme',
    mode: 'Mode',
    getSupported: 'Get Supported',
    saitaProSupport: 'SaitaPro Support',
    connectWithUs: 'Connect With Us',
    instagram: 'Instagram',
    facebook: 'Facebook',
    twitter: 'Twitter',
    Telegram: 'Telegram',
    discord: 'Discord',
    profileSettings: 'Settings',
    title1: 'Criar',
    title2: 'Pin',
    UNIQUEPIN: 'PIN ÚNICO',
    Touchid: 'Touch ID',
    Faceid: 'Face ID',
    Biometrics: 'Biometria',
    Back: 'Atrás',
    submit: 'Enviar',
    Approved: 'Aprovado',
    EnterPin: 'Inserir Pin',
    ConfirmPin: 'Confirmar Pin',
    CreatingPin: 'Criar PIN',
    PinReq: 'Este PIN de 6 dígitos será necessário para acessar a carteira',
    ImportWallet: 'IMPORTAR\nWALLET',
    CreateWallet: 'CRIAR\nWALLET',
    needHelp: 'Precisa de ajuda para se decidir?',
    walletText:
      'No SaitaPro você pode criar uma carteira sem custódia ou importar uma existente usando sua frase de segurança.',
    Importar: 'Importar',
    Wallet: 'Carteira',
    pasteText:
      'Cole ou digite sua frase de segurança na ordem correta com palavras separadas por espaços',
    name: 'Nome',
    NameWallet: 'Digite um nome para sua carteira',
    myWallet: 'My Wallet',//Change
    selectColor: 'Selecione uma cor',
    getStart: 'Iniciar',
    secure: 'Seguro',
    next: 'Seguinte',
    takeNote:
      'Anote a sua frase secreta e guarde-a em algum lugar seguro, se você perder essa frase talvez não consiga acessar sua carteira.',
    copyPhrase: 'Copiar frase',
    verify: 'Verificar',
    phrase: 'Frase',
    correctOrder:
      'Clique nas palavras na ordem correta da sua frase de segurança mostrada na tela anterior.',
    swap: 'Swap',
    get: 'Receber',
    send: 'Enviar',
    buy: 'Comprar',
    staking: 'Staking',
    noCoinFound: 'Nenhuma moeda encontrada',
    Hot: 'Hot',
    Gainer: 'Gainer',
    Loser: 'Loser',
    Vol: '24h Volume',
    Coin: 'Moeda',
    LastPrice: 'Último preço',
    HrChange: 'Movimento 24h',
    noGraphFound: 'Nenhum gráfico encontrado',
    SaitamaInu: 'Saitama',
    Home: 'INICIO',
    Market: 'MERCADO',
    Wallet_: 'CARTEIRA',
    Settings: 'DEFINIÇÕES',
    searchToken: 'Pesquisar token',
    searchUrl: 'Pesquise ou insira o URL do site ',
    Finance: 'Finanças',
    Exchanges: 'Exchanges',
    Games: 'Games',
    NFTs: 'NFTs',
    ok: 'Ok',
    Tokens: 'Tokens',
    Manage: 'Administrar',
    Security: 'Segurança',
    History: 'Histórico',
    Preferences: 'Preferencias',
    BackupOption: 'Opções de backup',
    contactUs: 'Contate-Nos',
    Logout: 'Sair',
    Notifications: 'Notificações',
    NoNoti: 'Desativar as notificações',
    select: 'Selecionar',
    searchBlock: 'Pesquisar Blockchain',
    NoHistory: 'Nenhuma transação encontrada !',
    addNewContact: 'Adicionar novo contato',
    nameYourContact: 'Dê um nome ao seu contato',
    enterNameHere: 'Digite o nome aqui',
    addWalletAddress: 'Adicionar endereço da carteira',
    address: 'Endereço',
    paste: 'Colar',
    saveContact: 'Salvar contato',
    addToken: 'Adicionar token',
    tokenSymbol: 'Símbolo Token',
    ethereum: 'Ethereum',
    binance: 'Binance',
    tokenContactAddress: 'Endereço do contrato de token',
    enterTokenContactAddress: 'Digite o endereço do contrato do token',
    tokenSymbol: 'Símbolo Token',
    enterTokenSymbol: 'Digite o símbolo do token',
    backUpOptions: 'Opções de backup',
    showRecoveryPhrase: 'Mostrar frase de recuperação',
    exportPrivateKeys: 'Exportar chaves privadas',
    changePasscode: 'Alterar código de acesso',
    enterSixDigitPin: 'Digite o PIN de 6 dígitos',
    reEnterSixDigitPin: 'Re-Enter the 6 digit Pin to access the wallet',

    history: 'Histórico',
    noTransactionFound: 'Nenhuma transação encontrada !',
    confirm: 'Confirme',
    pin: 'Pin',
    proceed: 'Continuar',
    pinIsRequired: 'Este pin de 6 dígitos será necessário',
    toAccessWallet: 'para aceder a carteira',
    transactionFees: 'Taxas de transação',
    advancedOptions: 'Opções avançadas',
    slow: 'lenta',
    average: 'Média',
    fast: 'Rápida',
    totalAmount: 'Valor total',
    currencyPreference: 'Preferência de moeda',
    contactEditedSuccessfully: 'Contato editado com sucesso',
    errorWhileEditingContact: 'Erro ao editar contato',
    editContact: 'Editar Contato',
    enterNameHere: 'Digite o nome aqui',
    nameYourContact: 'Dê um nome ao seu contato',
    addWalletAddress: 'Adicionar endereço da carteira',
    nameFieldIsRequired: 'O campo Nome é obrigatório',
    emailFieldIsRequired: 'O campo de e-mail é obrigatório',
    invalidEmail: 'O e-mail inserido é inválido',
    subjectFieldIsRequired: 'O campo assunto é obrigatório',
    messageFieldIsRequired: 'O campo de mensagem é obrigatório',
    addressFieldIsRequired: 'O campo de endereço é obrigatório',
    invalidAddress: 'Endereço inválido',
    requestSentSuccessfully: 'Solicitação enviada com sucesso',
    errorWhileSendingRequest: 'Erro ao enviar solicitação',
    getInTouch: 'Entre em contato',
    forSupport: 'para suporte',
    supportLine: 'This is the official SaitaPro support channel please fill all the fields and provide links and screenshots when applicable, we will contact you shortly through emails',
    // supportLine1: 'Este é o canal oficial de suporte do SaitaPro',
    supportLine2: 'preencha todos os campos e forneça links e',
    supportLine3: 'capturas de tela quando necessário, entraremos em contato',
    supportLine4: 'com você em breve através de e-mail',
    email: 'E-mail',
    subject: 'Assunto',
    message: 'Mensagem',
    walletAddress: 'Endereço da carteira',
    transactionLinks: 'Links de transação',
    attachScreenshots: 'Anexar imagens capturadas',
    takePhoto: 'Tirar foto',
    chooseFromGallery: 'Escolher da galeria',
    cancel: 'Cancelar',
    done: 'Feito',
    setAmount: 'Definir valor',
    copy: 'Copiar',
    share: 'Compartilhar',
    publicAddress: 'Endereço público',
    copyPhrase: 'Copiar frase',
    recoveryPhraseText:
      'Anote sua frase secreta e guarde-a em algum lugar seguro, se você perder essa frase talvez não consiga aceder a sua carteira.',
    toAccessTheWallet: 'para aceder a carteira',
    enterPin: 'Inserir Pin',
    enterNewPin: 'Insira o novo PIN',
    creatingAPin: 'Criar PIN',
    cameraAppPermission: 'Autorização de acesso a aplicação câmara',
    needAccessToCamera: 'SaitaPro App precisa de acesso à sua câmara',
    cameraPermissionDenied: 'Autorização de câmara negada',
    applock: 'Segurança',
    searchCurrency: 'Pesquisar moeda',
    wrongPin: 'Pin errado',
    lowBalanceAlert: 'Saldo muito baixo para enviar',
    cameraPermissionError: 'Erro de autorização de acesso a câmara',
    longPressToPaste: 'Pressione e segure para colar',
    contacts: 'Contatos',
    amount: 'Quantia',
    available: 'Disponível',
    transactionFeesBNB: 'Taxas de transação (BNB)',
    reset: 'Reset',
    gasPrice: 'Preço do Gas',
    pleaseEnterGasPrice: 'Por favor introduza o preço do Gas',
    confirmTransaction: 'Confirmar transação',
    selectCryptoContact:
      'Selecione o destinatário abaixo ou adicione um novo destinatário para enviar crypto ativos',
    areYouSure: 'Tem a certeza?',
    errorWhileDeletingContact: 'Erro ao excluir contato',
    contactDeletedSuccessfully: 'Contato excluído com sucesso',
    addNew: 'Adicionar novo',
    sendCrypto: 'Address Book',
    gasLimit: 'Limite de Gas',
    pleaseEnterGasLimit: 'Insira o limite de Gas',
    maxPriorityFeeGwei: 'Taxa de Prioridade Máxima (Gwei)',
    enterMaxPriorityFee: 'Insira a Taxa de Prioridade Máxima',
    maxFeeGwei: 'Taxa Máxima (Gwei)',
    maxFee: 'Taxa Máxima',
    stakingPools: 'Staking Pools',
    stakedOnly: 'Staked Only',
    live: 'Live',
    finished: 'Finalizadas',
    sortBy: 'Ordenar por',
    openSoon: 'aberto em breve',
    hot: 'Hot',
    totalStaked: 'Total staked',
    youSend: 'Você envia',
    btc: 'BTC',
    youReceive: 'Você recebe(Estimate)',
    rate: 'Ratio',
    inverseRate: 'Ratio Invertido',
    princeImpact: 'Impacto no Preço',
    gwei: 'Gwei',
    estimateGasFee: 'Taxa de Gas Estimada',
    liquidityFee: 'Taxa de Liquidez',
    uniSwap: 'UniSwap',
    panCakeSwap: 'PancakeSwap',
    transactionDetails: 'Detalhes da transação',
    transactionOn: 'Transação em:',
    viewInTransactionExplorer: 'Ver no explorador do navegador',
    chooselanguage: 'Escolha o seu idioma',
    dontshare: '*** Não compartilhe a frase inicial ***',
    selectLangProceed: 'Select your preferable language to proceed',
    easeToUse: 'Ease to use & highly secure',
    allTxMultCrpt: 'Allow transactions across multiple crypto currencies',
    importYourWallet: 'Import your wallet',
    createNewWallet: 'Create New Wallet',
    namingYourWallet:
      'Naming your wallet will help you track your multiple wallets easily.',
    nameYourWallet: 'Name your wallet',
    VerifyPhrase: 'Verify Phrase',
    enterMnemonoics: 'Enter Mnemonics',
    enterPhrase: 'Enter Phrase',
    Bulk: 'Bulk',
    addCustomToken: 'Add Custom Token',
    resetAPin: 'Reset PIN',
    enterPinAccessWallet: 'Enter the 6 Digit PIN to access the wallet',
    price: 'Price',
    WalletConnect: 'Wallet Connect',
    ScanQRCode: 'Escanear código QR',
    secretPhrases: 'Secret Phrases',
    useCryptoEasier: 'Using your crypto just got easier',//New
    limitlessWorld: 'in a limitless world of credit cards',
    getStarted: "Get Started",
    saitaPro: "SaitaPro",
    fangArt: 'FANG Art',
    saitamaStore: 'Saitama Store',
    saitaMarket: 'SaitaMarket',
    learn: 'Learn',
    getSupport: 'Get Support',
    uploadCSVFile: 'Upload CSV File',
    tokenName: 'Token Name',
    trade:'Trade',
  },
});
export let ThemeManager = new LocalizedStrings({
  //light theme

  //dark theme
  theme1: {
    colors: {
      iconBg: '#292929',
      inActiveColor: '#86868B',
      headerBg: '#1A1A1A',
      tabBackground: '#6E737E',
      wcbackground: '#343434',
      backgroundTheme: '#110f0f',
      dashboardBg: '#212121',
      backgroundColor: '#292929',//'#111111',
      statusBarColor: '#ffffff',
      borderColor: '#707070',
      textColor: '#FFFFFF',
      themeColor: 'dark',
      lightTextColor: '#86868B',//'#989898',
      placeholderTextColor: '#86868B',//'#6E737E',
      inputBorderColor: '#373737',//'#272C39',
      mnemonicsView: '#292929',//'#272C39',
      mnemonicsViewBorder:'#292929',
      viewBorderColor: '#303030',  //#86868B
      copyView: '#111111',
      bgLight: '#1E1E1E',
      copyBorder: '#5B4BE5',
      mnemonicsText: '#E8E7FF',
      mnemonicsSelectedText: '#E8E7FF',
      mnemonicsUnSelectedText: '#E8E7FF',
      searchTextColor: '#FFFFFF',
      dotColor: '#FFFFFF',
      defiBgColor: '#0C0C0C',
      btcBack: '#0C0C0C',
      txtAvailableColo: '#8389A2',
      csvTextColor: '#FFFBFB',
      chooseBorder: '#1D212B',
      importBorder: '#272C39',
      importView: '#111111',
      backupBorder: '#1D212B',
      backupView: '#000000',
      stakeColor: '#8F939E',
      swapBorder: '#1D212B',
      swapButtonsColor: '#8F939E',
      myEarn: '#FFFFFF',
      inactiveBtnText: '#80838E',
      inactiveBtn: '#272C39',
      amountField: '#272C39',
      amountBorder: '#272C39',
      claimBtn: '#8F939E',
      supplyBtnBg: '#6E737E',
      lightGrey: '#1D1D1B',
      searchBarBorder: '#272C39',
      checkBoxColor: '#272C39',
      inputBoxColor: '#272C39',
      viewAll: '#EA5AAC',
      toggleColor: '#2c2e30',
      login: '#989898',
      saitaOfferBorderColor: '#404040',
      saitaOfferbackground1: '#fff3',
      saitaOfferbackground2: 'transparent',
      saitaPaymentGradient: '#949494',
      saitaPaymentGradient1: '#111111',
      black_grey_bpay_deposit: '#8883',

      // new 
      bg: '#212121',//'#000',
      primary: '#0057FF',
      splashBg1: '#002233',
      splashBg2: '#000',//'#031A43',
      titleColor: '#fff',
      sell: '#FF060A',
      buy: '#34CC79',
      linearGradient1:'#321E3D',
      linearGradient2:'#082758',
      borderColorNew:"#ffffff50",
      lightButton:"#363636",
      headingText:'#fff',
      tabsBorder:'#303030',
      shadowColor:'#000000',
      iconColor:'#fff',
      tabBorder:'#303030',
      swapBg: '#292929',
      borderLineBorder:'#303030',
      cardHistoryImageBg:'#292929',
      colorLight:'#fff',
      dotLine:'#303030'
    },
    ImageIcons: {
      filter: images.filter,
      offerIcon: images.offerDark,
      bellIcon: images.Bell,
      historyIcon: images.historyDarkSetting,
      manageWallet: images.manageWalletDark,
      currencyPreferences: images.currencyPreferencesDark,
      chooseLanguage: images.chooseLanguageDark,
      backupWallet: images.backupWalletDark,
      modeIcon: images.modeDark,
      themeIcon: images.themeDark,
      securityIcon: images.securityDark,
      supportIcon: images.supportDark,
      iconBack: images.iconBackDark,
      forwardArrowIcon: images.forwardArrowDark,
      backgroundImage: images.backgroundImageDark,
      searchIcon: images.searchIconDark,
      marketActive: images.market_active,
      csvDownload: images.csvDownloadDark,
      history: images.historyDark2,
      setting: images.settingDark,
      congIcon: images.congDark,
      dropIconDown: images.dropIconDownDark,
      selectIcon: images.selectIconDark,
      historyActive: images.historyDark,
      defiActive: images.defiActiveDark,
      pulseAnim: images.pulsedark,
      lockpassword: images.lockwhite,
      card_logout: images.log_white,
      radioOn: images.radioOn,
      radioOff: images.radioOff,
      bnb: images.bnb,
      binance_pay: images.binance_pay,
      binance_pay_invert: images.binance_pay_dark,
      binance_text: images.binance_text,
      delImage: images.delImageDark,
      congratulationsIcon: images.congratulationsIcon,

      themeLight:images.themeDark,
      splashBg:images.darkThemeSplashBg,
      qrScreen:images.QRScreen,
      toggleOff:images.toggleOffNew
    },
  },
  theme2: {
    colors: {
      iconBg: '#FFFFFF',
      dashboardBg: '#FFFFFF',
      inActiveColor: '#86868B',
      headerBg: '#F3F3F3',
      tabBackground: '#6E737E',
      wcbackground: '#FAFAFA',
      backgroundTheme: '#ffffff',
      backgroundColor: '#ffffff',
      statusBarColor: '#f3f4f3',
      borderColor: '#707070',
      textColor: '#000000',
      bgLight: '#EFEFF6',
      themeColor: 'light',
      lightTextColor: '#6E737E',//Pending
      placeholderTextColor: '#A2A2A2',
      inputBorderColor: '#E5E5E5',
      mnemonicsView: '#fff',
      mnemonicsViewBorder:'#86868B',
      viewBorderColor: '#86868B',
      copyView: '#F3F3F3',
      copyBorder: '#F3F3F3',
      mnemonicsText: '#6E737E',
      mnemonicsSelectedText: '#EA5AAC',
      mnemonicsUnSelectedText: '#6E737E',
      searchTextColor: '#000000',
      defiBgColor: '#F3F3F3',
      btcBack: '#F3F3F3',
      txtAvailableColo: '#8389A2',
      dotColor: '#454444',
      csvTextColor: '#6E737E',
      chooseBorder: '#F3F3F3',
      importBorder: '#F3F3F3',
      importView: '#F3F3F3',
      backupBorder: '#ECECEC',
      backupView: '#F3F3F3',
      stakeColor: '#6E737E',
      swapBorder: '#F3F3F3',
      swapButtonsColor: '#00000029',
      myEarn: '#6E737E',
      inactiveBtnText: '#6E737E',
      inactiveBtn: '#F3F3F3',
      amountField: '#E5E5E5',
      amountBorder: '#E5E5E5',
      claimBtn: '#D4D4D4',
      supplyBtnBg: '#D4D4D4',

      lightGrey: '#b3b2b3',
      searchBarBorder: '#F3F3F3',
      checkBoxColor: '#A2A2A2',
      inputBoxColor: '#A2A2A2',
      viewAll: '#6E737E',
      toggleColor: '#d4d4d4',
      login: '#000000',
      saitaOfferBorderColor: '#ddd',
      saitaOfferbackground1: '#eee',
      saitaOfferbackground2: '#eee',
      saitaPaymentGradient: '#F3F3F3',
      saitaPaymentGradient1: '#ffffff',
      black_grey_bpay_deposit: '#000',


      //// newColors light 

      bg: '#fff',
      primary: '#0057FF',//'#0158FF',
      splashBg1: '#002233',
      splashBg2: '#031A43',
      titleColor: '#0158FF',//Pending
      sell: '#FF060A',
      buy: '#34CC79',
      linearGradient1:'#C0D9FF',
      linearGradient2:'#665AFF',
      borderColorNew:'#86868B',
      lightButton:"#D9D9D9",
      headingText:'#0057FF',
      tabsBorder:'#C3E1FD',
      shadowColor:'#000000',
      iconColor:'#86868B',
      tabBorder:'#D0D0D2',
      swapBg:'rgba(0, 87, 255,0.05)',
      borderLineBorder:'rgba(239, 239, 239,0.9)',
      cardHistoryImageBg:'#BED1EE',
      colorLight:'#86868B',
      dotLine:'#86868B'
    },

    ImageIcons: {
      filter: images.filter,
      offerIcon: images.offerLight,
      historyIcon: images.historyLightSetting,
      manageWallet: images.manageWalletLight,
      currencyPreferences: images.currencyPreferencesLight,
      chooseLanguage: images.chooseLanguageLight,
      backupWallet: images.backupWalletLight,
      modeIcon: images.modeLight,
      themeIcon: images.themeLight,
      securityIcon: images.securityLight,
      supportIcon: images.supportLight,
      iconBack: images.iconBackLight,
      forwardArrowIcon: images.forwardArrowLight,
      backgroundImage: images.backgroundImageLight,
      searchIcon: images.searchIconLight,
      marketActive: images.market_active_light,
      csvDownload: images.csvDownloadLight,
      epayWhiteVectorLight: images.epayWhiteVectorLight,
      iconLangSelectLight: images.iconLangSelectLight,
      congIcon: images.congLight,
      history: images.historyLight2,
      setting: images.settingLight,
      dropIconDown: images.dropIconDownLight,
      bellIcon: images.bellIconLight,
      selectIcon: images.selectIconLight,
      historyActive: images.historyLight,
      defiActive: images.defiActiveLight,
      pulseAnim: images.pulselight,
      lockpassword: images.lockblack,
      card_logout: images.log_black,

      radioOn: images.radioOn,
      radioOff: images.radioOff,
      bnb: images.bnb,
      binance_pay: images.binance_pay_dark,
      binance_pay_invert: images.binance_pay,
      binance_text: images.binance_text_dark,
      delImage: images.delImageDark,
      congratulationsIcon: images.congratulationsIcon,
      themeLight:images.themeLight,
      splashBg:images.lightThemeSplashBg,
      qrScreen:images.QRScreenLight,
      toggleOff:images.toggleOffNewLight
    },
  },
});
