import {StyleSheet} from 'react-native';
import {areaDimen, heightDimen, widthDimen} from '../../../Utils/themeUtils';
import {ThemeManager} from '../../../../ThemeManager';
import {Colors, Fonts} from '../../../theme';

export const styles = StyleSheet.create({
  viewPercentOuter: {
    marginTop: heightDimen(15),
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: widthDimen(5),
    backgroundColor: 'green',
  },
  coinSymbol: {
    width: areaDimen(34),
    height: areaDimen(34),
    borderRadius: areaDimen(40),
    resizeMode: 'contain',
    backgroundColor: ThemeManager.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  coinSymbolText: {
    fontFamily: Fonts.medium,
    fontSize: areaDimen(14),
    color: Colors.white,
  },
  amountView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginStart: heightDimen(16),
    height: heightDimen(30),
  },
  balanceLabelStyle: {
    fontFamily: Fonts.medium,
    fontSize: areaDimen(14),
    color: ThemeManager.colors.textColor,
  },
  convertedBalanceLabelStyle: {
    fontFamily: Fonts.medium,
    fontSize: areaDimen(14),
    color: ThemeManager.colors.textColor,
    marginHorizontal: widthDimen(16),
    marginTop: heightDimen(-10),
  },

  balanceValueStyle: {
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(12),
    color: ThemeManager.colors.searchTextColor,
    top: heightDimen(1),
  },
  txtTo: {
    fontSize: areaDimen(14),
    fontFamily: Fonts.semibold,
    marginTop: heightDimen(16),
    marginStart: widthDimen(30),
  },
  txtSending: {
    fontSize: areaDimen(16),
    fontFamily: Fonts.semibold,
    lineHeight: areaDimen(22),
    position: 'relative',
    zIndex: 222,
    marginLeft: widthDimen(-70),
  },
  btnStyle: {
    width: '86%',
    height: heightDimen(60),
    marginHorizontal: widthDimen(30),
    bottom: heightDimen(100),
  },
  customGrad: {
    position: 'absolute',
  },
  maxTextStyle: {
    color: ThemeManager.colors.textColor,
    fontFamily: Fonts.bold,
    fontSize: areaDimen(16),
  },
  btnStylen: {
    fontFamily: Fonts.regular,
    justifyContent: 'flex-end',
    backgroundColor: 'Transparent',
    borderWidth: 0,
    alignSelf: 'stretch',
    width: '100%',
    paddingHorizontal: widthDimen(20),
    borderRadius: areaDimen(10),
    marginBottom: heightDimen(20),
  },
  btnTextStyle: {
    fontFamily: Fonts.regular,
    fontSize: areaDimen(16),
    color: Colors.White,
    textAlign: 'left',
  },
  dropDownStyle: {
    backgroundColor: '#E5E5E5',
    borderRadius: areaDimen(10),
    shadowColor: '#fff',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    width: '88%',
  },
  rowStyle: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.04)',
    paddingLeft: widthDimen(20),
    backgroundColor: Colors.lightGrey2,
  },
  rowTextStyle: {
    fontFamily: Fonts.regular,
    fontSize: areaDimen(14),
    color: Colors.White,
    textAlign: 'left',
  },
  tabButtonsText: {
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(16),
    color: Colors.White,
    textAlign: 'left',
    lineHeight: heightDimen(19),
  },
  tabButtonsInActiveText: {
    fontFamily: Fonts.medium,
    fontSize: areaDimen(14),
    color: Colors.textColor,
    textAlign: 'left',
    lineHeight: heightDimen(19),
  },
  tab: {
    height: heightDimen(44),
    width: widthDimen(78),
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: ThemeManager.colors.inputBorderColor,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 10,
    marginHorizontal: widthDimen(22),
    marginTop: heightDimen(20),
  },
  swapStyle: {
    width: widthDimen(46),
    height: widthDimen(46),
    borderWidth: widthDimen(6),
    borderColor: ThemeManager.colors.bg,
    marginTop: heightDimen(-20),
    alignSelf: 'center',
    backgroundColor: ThemeManager.colors.primary,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    zIndex: 999,
  },
});
