import {StyleSheet} from 'react-native';
import {ThemeManager} from '../../../../../ThemeManager';
import {
  areaDimen,
  heightDimen,
  width,
  widthDimen,
} from '../../../../Utils/themeUtils';
import {Colors, Fonts} from '../../../../theme';

export default styles = StyleSheet.create({
  mainContainerStyle: {
    flex: 1,
  },
  borderLineStyle: {
    height: heightDimen(1),
    backgroundColor: ThemeManager.colors.borderColor,
  },
  cardView: {
    height: heightDimen(210),
    width: width - 42,
    alignSelf: 'center',
    borderRadius: areaDimen(24),
    overflow: 'hidden',
  },
  cardImageStyle: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    zIndex: 0,
  },
  loginView: {
    backgroundColor: 'white',
    position: 'absolute',
    right: 0,
    paddingHorizontal: areaDimen(18),
    paddingVertical: areaDimen(10),
    borderBottomLeftRadius: areaDimen(20),
    borderTopRightRadius: areaDimen(22),
    borderWidth: 1,
    top: areaDimen(0.5),
    overflow: 'hidden',
  },
  logintext: {
    fontFamily: Fonts.semibold,
    color: ThemeManager.colors.textColor,
    fontSize: areaDimen(16),
  },
  cardTitle: {
    fontFamily: Fonts.semibold,
    color: Colors.white,
    fontSize: areaDimen(14),
    lineHeight: heightDimen(18),
    maxWidth: '70%',
  },
  cardSubTitle: {
    fontFamily: Fonts.regular,
    color: Colors.white,
    fontSize: areaDimen(12),
    lineHeight: heightDimen(15),
    marginTop: areaDimen(4),
    maxWidth: '70%',
  },
  cardTitleView: {
    zIndex: 100,
    top: areaDimen(63),
    left: areaDimen(24),
  },
  categoryIconStyle: {
    height: areaDimen(22),
    width: areaDimen(22),
  },
  categoryTextStyle: {
    lineHeight: heightDimen(15),
    marginTop: areaDimen(15),
    color: ThemeManager.colors.primary,
    fontFamily: Fonts.medium,
    fontSize: areaDimen(12),
  },
  categoryView: {
    height: heightDimen(80),
    width: widthDimen(114),
    borderWidth: 1,
    borderRadius: areaDimen(12),
    borderColor: ThemeManager.colors.lightBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryMainView: {
    justifyContent: 'space-between',
    paddingHorizontal: areaDimen(22),
    marginVertical: areaDimen(24),
  },
  gradentButton: {
    // height: heightDimen(61),
    width: widthDimen(178),
    borderRadius: areaDimen(17),
    justifyContent: 'center',
    padding: areaDimen(10),
  },
  todayIcon: {
    height: areaDimen(40),
    width: areaDimen(40),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    borderRadius: areaDimen(13),
    marginRight: areaDimen(6),
  },
  todayTextTitle: {
    lineHeight: heightDimen(15),
    color: Colors.white,
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(12),
  },
  todayTextSubTitle: {
    color: Colors.white,
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(18),
    maxWidth: width / 4,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap:'wrap'
  },
  tabMainView: {
    borderWidth: areaDimen(1),
    justifyContent: 'space-between',
    marginHorizontal: areaDimen(22),
    borderRadius: areaDimen(22),
    padding: areaDimen(2),
    flexDirection: 'row',
    borderColor: ThemeManager.colors.lightBlue,
    alignItems: 'center',
  },
  tabTitile: {
    lineHeight: heightDimen(18),
    fontFamily: Fonts.medium,
    fontSize: areaDimen(14),
  },
  viewAllView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: areaDimen(22),
    marginBottom: areaDimen(14),
    // marginTop: areaDimen(30),
  },
  billTextStyle: {
    lineHeight: heightDimen(19),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(16),
    color: ThemeManager.colors.textColor,
  },
  viewAllTextStyle: {
    lineHeight: heightDimen(15),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(12),
    color: ThemeManager.colors.primary,
  },
  emptyTransactionsView: {
    alignItems: 'center',
    marginTop: areaDimen(50),
  },
  emptyIconStyle: {
    height: heightDimen(76),
    width: widthDimen(87),
    marginBottom: areaDimen(16),
  },
  emptyTextStyle: {
    lineHeight: heightDimen(18),
    fontFamily: Fonts.medium,
    fontSize: areaDimen(14),
    color: ThemeManager.colors.viewBorderColor,
    opacity:0.6
  },
  gradientView: {
    position: 'absolute',
    bottom: 0,
    zIndex: 200,
    paddingHorizontal: areaDimen(22),
    paddingVertical: areaDimen(11),
    borderTopRightRadius: areaDimen(20),
    borderWidth: 1,
    borderBottomLeftRadius: areaDimen(17),
  },
  cardName: {
    lineHeight: heightDimen(18),
    fontFamily: Fonts.regular,
    fontSize: areaDimen(14),
    color: Colors.White,
    paddingHorizontal: areaDimen(24),
    marginBottom: areaDimen(6),
  },
  cardNumber: {
    lineHeight: heightDimen(22),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(18),
    color: Colors.White,
    paddingHorizontal: areaDimen(24),
  },
  cardBrand: {
    lineHeight: heightDimen(19),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(16),
    color: Colors.White,
  },
  cardInnerView: {
    zIndex: 100,
    // top: areaDimen(61),
    paddingTop: areaDimen(61),
    height: '100%',
  },
  showIconStyle: {
    height: areaDimen(19),
    width: areaDimen(19),
    resizeMode: 'contain',
    tintColor: Colors.White,
    marginLeft: areaDimen(5),
  },
  cardOwnername: {
    lineHeight: heightDimen(18),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(14),
    color: Colors.White,
    position: 'absolute',
    right: areaDimen(26),
    top: areaDimen(26),
  },
  expenseDetailView:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: areaDimen(22),
    marginVertical: areaDimen(12),
    backgroundColor: Colors.cardBgColor,
    padding:areaDimen(10),
    borderRadius: areaDimen(12)
  },
  refundText:{
    lineHeight: heightDimen(15),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(12),
  },
  topUpTextStyle:{
    lineHeight: heightDimen(19),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(16),
    marginBottom: areaDimen(16),
    marginTop: areaDimen(4),
  },
  buttonView: {
    width: '100%',
    height: heightDimen(60),
    borderRadius: areaDimen(30),
    marginTop: areaDimen(8),
  },
  buttonText: {
    textAlign: 'center',
    color: Colors.white,
    fontSize: areaDimen(16),
    fontFamily: Fonts.semibold,
  },
  shimmerLoader: {
    height: areaDimen(100),
    width: '100%',
    borderRadius: areaDimen(10),
    marginBottom: areaDimen(12),
  },
  shimmerButtonLoader: {
    height: areaDimen(55),
    width: '100%',
    borderRadius: areaDimen(10),
    marginBottom: areaDimen(12),
  },
  transactionViewshimmer: {
    marginHorizontal: areaDimen(22),
    borderRadius: areaDimen(10),
    height: areaDimen(110),
    width: '90%',
    marginBottom: areaDimen(12),
  },
  shimmercategoryView: {
    height: heightDimen(80),
    width: widthDimen(114),
    borderRadius: areaDimen(10),
  },
  maxText: {
    lineHeight: heightDimen(19),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(16),
    marginBottom: areaDimen(16),
    marginTop: areaDimen(4),
  }, minText: {
    lineHeight: heightDimen(19),
    fontFamily: Fonts.semibold,
    fontSize: areaDimen(16),
    marginBottom: areaDimen(16),
    marginTop: areaDimen(4),
    textAlign:'right'
  },
  cardLockImageStyle: {
    height: areaDimen(75),
    width: areaDimen(75),
    alignSelf: 'center',
    marginBottom:areaDimen(16)
  },
  cardLockTitle: {
    textAlign: 'center',
    alignSelf: 'center',
    color: ThemeManager.colors.textColor,
    fontSize: areaDimen(16),
    fontFamily: Fonts.semibold,
    lineHeight: heightDimen(19),
    maxWidth: width / 1.2,
  },
  cardLockSubTitle: {
    textAlign: 'center',
    alignSelf: 'center',

    color: Colors.red,
    fontSize: areaDimen(14),
    lineHeight: heightDimen(18),
    marginTop: areaDimen(8),
    maxWidth: width / 1.2,
    fontFamily: Fonts.semibold,
  },
});
