// import { IMG_URL } from '../Endpoints';
const LightThemePath = '../../assets/images/iconWhite/';
const DarkThemePath = '../../assets/images/iconDark/';
const images = {
  hideShow: require('../../assets/images/hideShow.png'),
  LoaderJson: require('../../assets/images/loader.json'),
  rightArrow: require('../../assets/images/rightArrow.png'),
  SplashAnimation: require('../../assets/images/Splash Animation.json'),
  SplashAnimationDark: require('../../assets/images/Splash Animation.json'),
  Loadclock: require('../../assets/images/Loadclock.json'),
  Kycerror: require('../../assets/images/Kycerror.json'),
  KycSuccess: require('../../assets/images/KycSuccess.json'),
  DoneKyc: require('../../assets/images/DoneKyc.json'),
  pulse: require('../../assets/images/pulse.json'),
  pulsedark: require('../../assets/images/pulsedark.json'),
  pulselight: require('../../assets/images/pulselight.json'),
  uploadWhite: require('../../assets/images/uploadWhite.png'),
  tickWhite: require('../../assets/images/tickWhite.png'),
  uploadImage: require('../../assets/images/gallery.png'),
  male: require('../../assets/images/Male.png'),
  female: require('../../assets/images/Female.png'),
  SaitaproAnimation: require('../../assets/images/Saitapro_Animation.json'),
  // splash_logo: IMG_URL + 'Add.png',
  Textanimation: require('../../assets/images/SplashAnimation.json'),
  newAnimation: require('../../assets/images/newAnimation.json'),
  animRound: require('../../assets/images/anim_round.json'),

  leftArrow: require('../../assets/images/leftArrow.png'),
  cancel: require('../../assets/images/cancel.png'),
  // LoaderJson: require('../../assets/images/Loader.json'),
  // rightArrow: require('../../assets/images/rightArrow.png'),
  // splash_logo: IMG_URL + 'Add.png',
  // leftArrow: require('../../assets/images/leftArrow.png'),
  share: require('../../assets/images/share.png'),
  radioOn: require('../../assets/images/radioOn.png'),
  radioOff: require('../../assets/images/radioOff.png'),
  logout: require('../../assets/images/logout.png'),
  saita: require('../../assets/images/saita.png'),
  hmask: require('../../assets/images/hmask.png'),
  mask: require('../../assets/images/mask.png'),
  FANG: require('../../assets/images/FANG.png'),
  learn: require('../../assets/images/learn.png'),
  refral: require('../../assets/images/refral.png'),
  contact: require('../../assets/images/contact.png'),
  sendArrow: require('../../assets/images/sendArrow.png'),
  SaitaPro: require('../../assets/images/SaitaPro.png'),
  SaitaProStraight: require('../../assets/images/saita_pro_straight.png'),
  redit: require('../../assets/images/redit.png'),
  instagram: require('../../assets/images/instagram.png'),
  block: require('../../assets/images/block.png'),
  security: require('../../assets/images/security.png'),
  prefrence: require('../../assets/images/prefrence.png'),
  walletConnect: require('../../assets/images/walletConnect.png'),
  facebook: require('../../assets/images/facebook.png'),
  twitter: require('../../assets/images/twitter.png'),
  telegram: require('../../assets/images/telegram.png'),
  roundArw: require('../../assets/images/roundArw.png'),
  boxicon: require('../../assets/images/boxicon.png'),
  box2: require('../../assets/images/box2.png'),
  box: require('../../assets/images/box.png'),
  learnMore: require('../../assets/images/learnMore.png'),
  bitcoin: require('../../assets/images/Bitcoin.png'),
  scan: require('../../assets/images/scanIcon.png'),
  Bell: require('../../assets/images/bellIcon.png'),
  hamburger: require('../../assets/images/hamburger.png'),
  splash_bg: require('../../assets/images/splashIconbg.png'),
  backgroundd: require('../../assets/images/background.png'),
  splashdarkbg: require('../../assets/images/splashdarkbg.png'),
  logo: require('../../assets/images/logo.png'),
  downGraph: require('../../assets/images/downGraph.png'),
  DownArw: require('../../assets/images/DownArw.png'),
  AppNamebg: require('../../assets/images/AppNamebg.png'),
  AppName: require('../../assets/images/AppName.png'),
  Search: require('../../assets/images/Search.png'),
  graphGreen: require('../../assets/images/graphGreen.png'),
  iconWolf: require('../../assets/images/iconWolf.png'),
  impactXP: require('../../assets/images/impactXP.png'),
  shirYo: require('../../assets/images/shirYo.png'),
  Xp: require('../../assets/images/Xp.png'),
  mandox: require('../../assets/images/mandox.png'),
  ETH: require('../../assets/images/ETH.png'),
  solana: require('../../assets/images/solana.png'),
  staking: require('../../assets/images/staking.png'),
  headerAppName: require('../../assets/images/headerAppName.png'),
  BYsaita: require('../../assets/images/BYsaita.png'),
  WalletSecurity: require('../../assets/images/WalletSecurity.png'),
  Add: require('../../assets/images/Add.png'),
  faceID: require('../../assets/images/faceID.png'),
  back: require('../../assets/images/back.png'),
  emailIcon: require('../../assets/images/emailIcon.png'),
  lockIcon: require('../../assets/images/lockIcon.png'),
  backIcon: require('../../assets/images/backIcon.png'),
  saita_logo: require('../../assets/images/saita_logo_.png'),
  active_tab_bg: require('../../assets/images/active_tab_bg.png'),
  home_active: require('../../assets/images/home_active.png'),
  home_inactive: require('../../assets/images/Home_inactive.png'),
percentage:require('../../assets/images/percentage.png'),
  settings_inactive: require('../../assets/images/settings_inactive.png'),
  browser_inactive: require('../../assets/images/browser_inactive.png'),
  wallet_active: require('../../assets/images/Wallet_active.png'),
  wallet_inactive: require('../../assets/images/Wallet_inactive.png'),

  settings_active: require('../../assets/images/settings_active.png'),
  browser_active: require('../../assets/images/browser_active.png'),
  slider_img: require('../../assets/images/slider_img.png'),
  slider_saita: require('../../assets/images/slider_saita.png'),
  slider: require('../../assets/images/slider.png'),
  Buy: require('../../assets/images/Buy.png'),
  get: require('../../assets/images/get.png'),
  send: require('../../assets/images/send.png'),
  swap: require('../../assets/images/swap.png'),
  // impactXP: require('../../assets/images/impactXP.png'),
  kishmoto: require('../../assets/images/kishmoto.png'),
  graphDown: require('../../assets/images/graphDown.png'),
  up: require('../../assets/images/up.png'),
  down: require('../../assets/images/down.png'),
  graphUp: require('../../assets/images/graphUp.png'),
  graph: require('../../assets/images/graph.png'),
  BtcIconSwap: require('../../assets/images/BtcIconSwap.png'),
  swapIcon: require('../../assets/images/swapIcon.png'),
  ethSwapIcon: require('../../assets/images/ethSwapIcon.png'),
  Pathicon: require('../../assets/images/Pathicon.png'),
  uniIcon: require('../../assets/images/uniIcon.png'),
  bunnyIcon: require('../../assets/images/bunnyIcon.png'),
  searchIcon: require('../../assets/images/searchIcon.png'),
  financeIcon: require('../../assets/images/financeIcon.png'),
  exchangesIcon: require('../../assets/images/exchangesIcon.png'),
  gamesIcon: require('../../assets/images/gamesIcon.png'),
  creditCard: require('../../assets/images/creditCard.png'),
  editIcon: require('../../assets/images/editIcon.png'),
  backIconArrow: require('../../assets/images/backIconArrow.png'),
  qrCode: require('../../assets/images/qrCode.png'),
  dashboardSlider: require('../../assets/images/sliderImg.png'),
  plusIconCircleBorder: require('../../assets/images/plusIconCircleBorder.png'),
  plusIconWhite: require('../../assets/images/plusIconWhite.png'),
  bnb: require('../../assets/images/bnb.png'),
  polygon: require('../../assets/images/polygon.png'),
  financeIcon1: require('../../assets/images/financeIcon1.png'),
  financeIcon2: require('../../assets/images/financeIcon2.png'),
  financeIcon3: require('../../assets/images/financeIcon3.png'),
  financeIcon4: require('../../assets/images/financeIcon4.png'),

  exchangeIcon1: require('../../assets/images/exchangeIcon1.png'),
  exchangeIcon2: require('../../assets/images/exchangeIcon2.png'),
  exchangeIcon3: require('../../assets/images/exchangeIcon3.png'),
  exchangeIcon4: require('../../assets/images/exchangeIcon4.png'),

  gamesIcon1: require('../../assets/images/gamesIcon1.png'),
  gamesIcon2: require('../../assets/images/gamesIcon2.png'),
  gamesIcon3: require('../../assets/images/gamesIcon3.png'),
  gamesIcon4: require('../../assets/images/gamesIcon4.png'),

  nftIcon1: require('../../assets/images/nftIcon1.png'),
  nftIcon2: require('../../assets/images/nftIcon2.png'),
  nftIcon3: require('../../assets/images/nftIcon3.png'),
  nftIcon4: require('../../assets/images/nftIcon4.png'),

  // BtcIconSwap: require('../../assets/images/BtcIconSwap.png'),
  // swapIcon: require('../../assets/images/swapIcon.png'),
  // ethSwapIcon: require('../../assets/images/ethSwapIcon.png'),
  // Pathicon: require('../../assets/images/Pathicon.png'),
  // uniIcon: require('../../assets/images/uniIcon.png'),
  // bunnyIcon: require('../../assets/images/bunnyIcon.png'),
  backpinkIcon: require('../../assets/images/backpinkIcon.png'),
  downIcon: require('../../assets/images/downIcon.png'),
  scanner: require('../../assets/images/icon_address.png'),
  address: require('../../assets/images/icon_address_book.png'),
  modal_close_icon: require('../../assets/images/modal_close_icon.png'),
  icon_successfully_sent: require('../../assets/images/icon_terms_selected.png'),
  transaction_erro_icon: require('../../assets/images/transaction_erro_icon.png'),
  icon_sent: require('../../assets/images/icon_sent.png'),
  icon_receive_transaction: require('../../assets/images/icon_receive_transaction.png'),
  time_icon: require('../../assets/images/icon_time.png'),
  icon_receive: require('../../assets/images/icon_receive.png'),
  bin: require('../../assets/images/bin.png'),
  edit: require('../../assets/images/pencil.png'),
  attachment: require('../../assets/images/attachment.png'),
  checkbox_default: require('../../assets/images/checkbox_default.png'),
  checkbox_active: require('../../assets/images/checkbox.png'),
  bulk_icon: require('../../assets/images/bulk_icon.png'),
  reload: require('../../assets/images/reload.png'),
  delete: require('../../assets/images/trash.png'),
  ukFlag: require('../../assets/images/uk_flag.png'),
  spainFlag: require('../../assets/images/spain_flag.png'),
  iconBack: require('../../assets/images/back_icon.png'),
  selectLangBg: require('../../assets/images/dummy_bg.png'),
  IconCopyInside: require('../../assets/images/Icon_copy_inside.png'),
  HistoryActive: require('../../assets/images/history_active.png'),
  HistoryInActive: require('../../assets/images/history_inactive.png'),
  iconSelectedCurrency: require('../../assets/images/icon_selected_currency.png'),
  imgFangArt: require('../../assets/images/imgFangArt.png'),
  imgSubTract: require('../../assets/images/Subtraction.png'),
  imgSaitaMarket: require('../../assets/images/saitaMarket.png'),
  imgLearn: require('../../assets/images/imgLearn.png'),
  iconMarket: require('../../assets/images/icon_market.png'),
  defiActiveNew: require('../../assets/images/Defi_active.png'),
  defiInActiveNew: require('../../assets/images/defi_inactive.png'),
  imgBtcSymbol: require('../../assets/images/imgBtcSymbol.png'),
  iconColoredRefresh: require('../../assets/images/iconColoredRefresh.png'),
  ethBtcCombo: require('../../assets/images/ethBtcCombo.png'),
  addImage: require('../../assets/images/addImage.png'),
  lockwhite: require('../../assets/images/lockwhite.png'),
  lockblack: require('../../assets/images/lockblack.png'),

  log_black: require('../../assets/images/log_black.png'),
  log_white: require('../../assets/images/log_white.png'),

  //light theme icon
  historyLightSetting: require(LightThemePath + 'historyLight.png'),
  offerLight: require(LightThemePath + 'offer.png'),
  manageWalletLight: require(LightThemePath + 'manageWalletLight.png'),
  currencyPreferencesLight: require(LightThemePath +
    'currencyPreferencesLight.png'),
  chooseLanguageLight: require(LightThemePath + 'chooseLanguageLight.png'),
  backupWalletLight: require(LightThemePath + 'backupWalletLight.png'),
  forwardArrowLight: require(LightThemePath + 'forwardArrowLight.png'),
  searchIconLight: require(LightThemePath + 'searchIconLight.png'),
  modeLight: require(LightThemePath + 'modeLight.png'),
  themeLight: require(LightThemePath + 'themeLight.png'),
  securityLight: require(LightThemePath + 'securityLight.png'),
  supportLight: require(LightThemePath + 'supportLight.png'),
  telegramIcon: require(LightThemePath + 'telegram.png'),
  twitterIcon: require(LightThemePath + 'twitter.png'),
  fbIcon: require(LightThemePath + 'fbIcon.png'),
  discord: require(LightThemePath + 'discord.png'),
  instagramIcon: require(LightThemePath + 'instagram.png'),
  iconBackLight: require(LightThemePath + 'iconBackLight.png'),
  backgroundImageLight: require(LightThemePath + 'backgroundImageLight.png'),
  market_active_light: require('../../assets/images/marketBlue.png'),
  csvDownloadLight: require(LightThemePath + 'csvDownload.png'),
  epayWhiteVectorLight: require(LightThemePath + 'epayWhiteVector.png'),
  iconLangSelectLight: require(LightThemePath + 'iconLangSelect.png'),
  congLight: require(LightThemePath + 'congLight.png'),
  addIcon: require(LightThemePath + 'addIcon.png'),
  historyLight2: require(LightThemePath + 'history.png'),
  settingLight: require(LightThemePath + 'setting.png'),
  dropIconDownLight: require(LightThemePath + 'dropIconDownBlack.png'),
  bellIconLight: require(LightThemePath + 'bellIcon.png'),
  selectIconLight: require(LightThemePath + 'iconCheck1.png'),
  historyLight: require(LightThemePath + 'history_active.png'),
  defiActiveLight: require(LightThemePath + 'defi_active.png'),
  iconInfo: require(LightThemePath + 'iconInfo.png'),

  //dark theme icon
  offerDark: require(DarkThemePath + 'offer.png'),
  securityDark: require(DarkThemePath + 'securityDark.png'),
  backupWalletDark: require(DarkThemePath + 'backupWalletDark.png'),
  chooseLanguageDark: require(DarkThemePath + 'chooseLanguageDark.png'),
  currencyPreferencesDark: require(DarkThemePath +
    'currencyPreferencesDark.png'),
  historyDarkSetting: require(DarkThemePath + 'historyDark.png'),
  manageWalletDark: require(DarkThemePath + 'manageWalletDark.png'),
  supportDark: require(DarkThemePath + 'supportDark.png'),
  modeDark: require(DarkThemePath + 'modeDark.png'),
  searchIconDark: require(DarkThemePath + 'searchIconDark.png'),
  themeDark: require(DarkThemePath + 'themeDark.png'),
  iconBackDark: require(DarkThemePath + 'iconBackDark.png'),
  forwardArrowDark: require(DarkThemePath + 'forwardArrowDark.png'),
  backgroundImageDark: require(DarkThemePath + 'backgroundImageDark.png'),
  market_active: require('../../assets/images/market_active.png'),
  market_inactive: require('../../assets/images/market_inactive.png'),
  csvDownloadDark: require(DarkThemePath + 'csvDownload.png'),
  historyDark2: require(DarkThemePath + 'history.png'),
  settingDark: require('../../assets/images/setting.png'),
  congDark: require(DarkThemePath + 'congDark.png'),
  dropIconDownDark: require(DarkThemePath + 'dropIconDownWhite.png'),
  bellIconDark: require(LightThemePath + 'bellIcon.png'),
  managaeIconDark: require(DarkThemePath + 'managaeIconDark.png'),
  historyDark: require(DarkThemePath + 'history_active.png'),
  defiActiveDark: require(DarkThemePath + 'defi_active.png'),

  btc_s: require('../../assets/images/btc_s.png'),
  eth_s: require('../../assets/images/eth_s.png'),
  saita_stake: require('../../assets/images/saita_stake.png'),
  cards: require('../../assets/images/cards.png'),
  cardblackform: require('../../assets/images/cardblackform.png'),
  physical_card: require('../../assets/images/physical_card.png'),
  virtual_cards: require('../../assets/images/virtual_cards.png'),

  cardBlack: require('../../assets/images/cardBlack.jpeg'),
  cardDiamond: require('../../assets/images/cardDiamond.jpeg'),
  cardGold: require('../../assets/images/cardGold.jpeg'),
  kycReview: require('../../assets/images/kycReview.json'),
  alertIcon: require('../../assets/images/alertIcon.png'),
  close: require('../../assets/images/close.png'),
  unCheckStar: require('../../assets/images/unCheckStar.png'),
  checkStar: require('../../assets/images/checkStar.png'),
  sort: require('../../assets/images/sort.png'),
  del: require('../../assets/images/del.png'),
  send_notification: require('../../assets/images/send_notification.png'),
  receive_notification: require('../../assets/images/receive_notification.png'),
  warning: require('../../assets/images/warning.png'),

  deposit: require('../../assets/images/deposit.png'),
  eye_card: require('../../assets/images/eye_card.png'),
  open_eye: require('../../assets/images/openEye.png'),
  epaylogo: require('../../assets/images/epaylogo.png'),
  icon_walletConnect: require('../../assets/images/icon_account_wallet.png'),
  selectIconDark: require(DarkThemePath + 'iconCheck.png'),
  saita_card_black: require('../../assets/images/saita_card_black.png'),
  binance_pay: require('../../assets/images/binance_pay.png'),
  binance_pay_dark: require('../../assets/images/binance_pay_dark.png'),
  usdt_logo: require('../../assets/images/usdt_logo.png'),
  binance_logo: require('../../assets/images/binance_log.png'),
  binance_text: require('../../assets/images/binance_text.png'),
  binance_text_dark: require('../../assets/images/binance_text_dark.png'),
  epay_white: require('../../assets/images/epay_white.png'),
  visa: require('../../assets/images/visa.png'),
  mastercard: require('../../assets/images/mastercard.png'),
  id_front: require('../../assets/images/id_front.png'),
  id_back: require('../../assets/images/id_back.png'),
  selfie_kyc: require('../../assets/images/selfie_kyc.png'),
  google_pay: require('../../assets/images/google_pay.png'),
  apple_pay: require('../../assets/images/apple_pay.png'),
  new: require('../../assets/images/new.png'),

  kycRejected: require('../../assets/images/kycRejected.json'),
  pinkWallet: require('../../assets/images/pinkWallet.png'),
  popUpImage: require('../../assets/images/popUpImage.png'),
  newIcon: require('../../assets/images/newIcon.png'),
  usdtRound: require('../../assets/images/usdtRound.png'),
  infoBPay: require('../../assets/images/infoBPay.png'),
  splashLogo: require('../../assets/images/splashLogoWhite.png'),
  splashLogoBottom: require('../../assets/images/splashLogoWhiteBottom.png'),
  english: require('../../assets/images/English.png'),
  espanol: require('../../assets/images/Espanol.png'),
  france: require('../../assets/images/France.png'),
  italian: require('../../assets/images/Italian.png'),
  portugues: require('../../assets/images/Portugues.png'),
  check: require('../../assets/images/check.png'),
  saitaCard: require('../../assets/images/SaitaCard.png'),
  buy: require('../../assets/images/Buy.png'),
  deutsch: require('../../assets/images/Deutsch.png'),
  delImageDark: require('../../assets/images/iconDark/delImage.png'),
  congratulationsIcon: require('../../assets/images/congratulationsIcon.png'),
  walletIcon: require('../../assets/images/walletIcon.png'),
  welcomeIcon: require('../../assets/images/welcomeIcon.png'),
  referIcon: require('../../assets/images/referIcon.png'),
  icon_send: require('../../assets/images/icon_send.png'),
  icon_receive: require('../../assets/images/icon_receive.png'),
  saitaPro_icon: require('../../assets/images/saitaPro_icon.png'),
  upload_file_icon: require('../../assets/images/upload_file_icon.png'),
  icon_manage_wallet: require('../../assets/images/icon_manage_wallet.png'),
  icon_stake: require('../../assets/images/icon_stake.png'),
  cross: require('../../assets/images/cross.png'),
  huobi: require('../../assets/images/Huobi.png'),
  filter: require('../../assets/images/filter.png'),
  icon_liquidity: require('../../assets/images/icon_liquidity.png'),
  icon_history: require('../../assets/images/icon_history.png'),
  icon_currency: require('../../assets/images/icon_currency.png'),
  icon_language: require('../../assets/images/icon_language.png'),
  icon_security: require('../../assets/images/icon_security.png'),
  icon_wallet_connect: require('../../assets/images/icon_wallet_connect.png'),
  icon_bulk_transfer: require('../../assets/images/icon_bulk_transfer.png'),
  icon_saita_support: require('../../assets/images/icon_saita_support.png'),
  icon_logout: require('../../assets/images/icon_logout.png'),
  not_found: require('../../assets/images/not_confirmed.png'),
  downloadCardFeature: require('../../assets/images/downloadCardFeature.png'),
  depositCard: require('../../assets/images/depositCard.png'),
  icon_paste: require('../../assets/images/icon_paste.png'),
  toggleOn: require('../../assets/images/toggleOn.png'),
  toggleOff: require('../../assets/images/toggleOff.png'),
  toggleOffLight: require('../../assets/images/toggleOffLight.png'),
  recieve: require('../../assets/images/recieve.png'),

  formatImage: require('../../assets/images/formatImage.png'),
  downloadCardFeature: require('../../assets/images/downloadCardFeature.png'),
  depositCard: require('../../assets/images/depositCard.png'),
  modalCancel: require('../../assets/images/modalCancel.png'),
  cardPayWallet: require('../../assets/images/cardPayWallet.png'),
  cardPayGateWay: require('../../assets/images/cardPayGateWay.png'),
  arrowBack:require('../../assets/images/arrowBack.png'),
  bookmark:require('../../assets/images/bookmark.png'),
  bookmarkActive:require('../../assets/images/bookmarkActive.png'),
  dot:require('../../assets/images/dot.png'),
  contactSaitaSupport:require('../../assets/images/contactSaitaSupport.png'),
  QRScreen:require('../../assets/images/QRScreen.png'),
  QRScreenLight:require('../../assets/images/QRScreenLight.png'),
  tradeInActive:require('../../assets/images/tradeInActive.png'),
  tradeActive:require('../../assets/images/tradeActive.png'),
  fullArrow:require('../../assets/images/fullArrow.png'),
  learn_icon: require('../../assets/images/learn_icon.png'),
  fang_icon: require('../../assets/images/fang_icon.png'),
  saitama_store_icon: require('../../assets/images/saitama_store_icon.png'),
  saita_markit_icon:  require('../../assets/images/saita_markit_icon.png'),
  support_icon: require('../../assets/images/support_icon.png'),
  viewWithShadow: require('../../assets/images/viewWithShadow.png'),
  walletDownArrow: require('../../assets/images/walletDownArrow.png'),
  welcomebg: require('../../assets/images/welcomebg.png'),
  SaitaPro_H5: require('../../assets/images/SaitaPro_H5.png'),
  amountHideIcon: require('../../assets/images/amountHideIcon.png'),
  arrow_filled: require('../../assets/images/arrow_filled.png'),
  bsc_with_shadow: require('../../assets/images/bsc_with_shadow.png'),
  eth_with_shadow:  require('../../assets/images/eth_with_shadow.png'),
  toggleOffNew:  require('../../assets/images/toggleOffNew.png'),
  toggleOffNewLight:  require('../../assets/images/toggleOffLight.png'),
  themeLight:require('../../assets/images/themeLight.png'),
  lightThemeSplashBg:require('../../assets/images/lightThemeSplashBg.png'),
  darkThemeSplashBg:require('../../assets/images/darkThemeSplashBg.png'),
  themeDark:require('../../assets/images/themeDark.png'),
  wcAlert:require('../../assets/images/wcAlert.png'),
  //----------------------------------------------------------------
  cardInfo:require('../../assets/images/cardInfo.png'),
  circleDoller:require('../../assets/images/circleDoller.png'),
  topUp:require('../../assets/images/topUp.png'),
  manage:require('../../assets/images/manage.png'),
  emptyTransactions:require('../../assets/images/emptyTransactions.png'),
  dailyLimit:require('../../assets/images/dailyLimit.png'),
  cardBg:require('../../assets/images/cardBg.png'),
  lockCard:require('../../assets/images/lockCard.png'),
  replaceCard:require('../../assets/images/replaceCard.png'),
  rightCircleArrow:require('../../assets/images/rightCircleArrow.png'),
  pinLock:require('../../assets/images/pinLock.png'),
  blueTick:require('../../assets/images/blueTick.png'),
  circleCross:require('../../assets/images/circleCross.png'),
  circleCardLock:require('../../assets/images/circleCardLock.png'),
  eyeOpened: require("../../assets/images/eyeOpened.png"),
  eyeClosed: require("../../assets/images/eyeClosed.png"),
  bluecardImage: require("../../assets/images/bluecardImage.png"),
  circleAddWallet: require("../../assets/images/circleAddWallet.png"),
  usdtIcon: require("../../assets/images/usdtIcon.png"),
  redDoller: require("../../assets/images/redDoller.png"),
  blueCrown: require("../../assets/images/blueCrown.png"),
  tiltCard: require("../../assets/images/tiltCard.png"),
  circleBlueTick: require("../../assets/images/circleBlueTick.png"),
  blueLike: require("../../assets/images/blueLike.png"),
};

export default images;
