import {StyleSheet, Dimensions, Platform} from 'react-native';
import {ThemeManager} from '../../../../ThemeManager';
import {Colors, Fonts} from '../../../theme';
import fonts from '../../../theme/Fonts';
import {areaDimen, heightDimen, widthDimen} from '../../../Utils/themeUtils';

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: widthDimen(10),
    position: 'relative',
  },
  lastDepositText: {
    color: '#B0CBFB',
    fontFamily: fonts.medium,
    fontSize: areaDimen(13),
  },
  imgcards: {
    backgroundColor: 'white',
    height: heightDimen(265),
    width: widthDimen(184),
    borderRadius: 25,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: heightDimen(Platform.OS == 'ios' ? 20 : 5),
  },
  txtCardone: {
    color: Colors.white,
    fontFamily: fonts.bold,
    fontSize: areaDimen(18),
    textTransform: 'capitalize',
    letterSpacing: 1,
  },
  txtCardred: {
    color: ThemeManager.colors.textColor,
    fontFamily: fonts.medium,
    fontSize: areaDimen(10),
  },

  imgCopyInside: {
    height: heightDimen(15),
    width: widthDimen(15),
  },
  balText: {
    color: ThemeManager.colors.textColor,
    fontFamily: fonts.bold,
    fontSize: areaDimen(20),
    // lineHeight: areaDimen(24),
    marginTop: heightDimen(6),
  },
  eyeStyle: {
    position: 'absolute',
    alignSelf: 'flex-end',
    top: heightDimen(30),
    right: widthDimen(25),
    zIndex: 1,
  },
  totalBal: {
    color: ThemeManager.colors.textColor,
    fontFamily: fonts.regular,
    fontSize: areaDimen(16),
    marginTop: heightDimen(Platform.OS == 'ios' ? 20 : 10),
  },
  activeCardName: {
    minHeight: 100,
    borderRadius: areaDimen(17),
    justifyContent: 'center',
    marginTop: heightDimen(70),
    marginBottom: heightDimen(45),
  },
  txtstar: {
    color: ThemeManager.colors.textColor,
    fontFamily: fonts.medium,
    fontSize: areaDimen(14),
    paddingVertical: heightDimen(10),
    letterSpacing: 1,
    // marginTop: heightDimen(10),
  },
  txtdate: {
    color: Colors.white,
    fontFamily: fonts.medium,
    fontSize: areaDimen(12),
    marginTop: 4,
    letterSpacing: 1,
  },
  txtcvv: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontFamily: fonts.medium,
    fontSize: areaDimen(10),
  },
  cardIconImage: {
    height: areaDimen(38),
    width: areaDimen(38),
    borderRadius: areaDimen(15),
  },
  notFoundImage: {height: areaDimen(123), width: areaDimen(123)},
  notFoundText: {
    color: ThemeManager.colors.inActiveColor,
    fontFamily: fonts.medium,
    fontSize: areaDimen(20),
    lineHeight: areaDimen(24),
    marginTop: heightDimen(34),
  },
  cardContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notIConContainer: {
    height: areaDimen(38),
    width: areaDimen(38),
    backgroundColor: Colors.buttonColor2,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: areaDimen(40),
  },
  coinName: {
    color: ThemeManager.colors.textColor,
    fontFamily: fonts.medium,
    fontSize: areaDimen(16),
    lineHeight: areaDimen(19),
    marginBottom: heightDimen(4),
    // textTransform:'capitalize'
  },
  tabStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: heightDimen(40),
    width: widthDimen(122.7),
  },
  tabText: {
    color: Colors.white,
    fontSize: areaDimen(16),
    fontFamily: Fonts.medium,
    lineHeight: heightDimen(19),
  },
  tabsContainer: {
    flexDirection: 'row',
    width: widthDimen(370),
    alignSelf: 'center',
    borderRadius: 100,
    marginTop: heightDimen(20),
    // borderColor: '#303030',
    borderWidth: 1,
    padding: areaDimen(5),
  },
  textInput: {
    color: Colors.white,
    fontSize: 14,
    // alignSelf: 'center',
    textAlign: 'center',
    // fontFamily: fonts.regular,
    marginRight: 5,
    // backgroundColor:'red',
    // width:'95%'
  },
  balanceBoxStyle: {
    width: widthDimen(370),
    paddingTop: heightDimen(25),
    paddingBottom: heightDimen(31),
    borderRadius: areaDimen(25),
    // alignItems: 'center',
    // justifyContent: 'center',
    alignSelf: 'center',
    marginTop: heightDimen(20),
    height: heightDimen(184),
    position: 'relative',
  },
  titleTextStyle: {
    color: Colors.white,
    fontFamily: Fonts.regular,
  },
  balanceTextStyle: {
    marginLeft: widthDimen(25),
    color: Colors.white,
    fontSize: areaDimen(34),
    fontFamily: Fonts.semibold,
    lineHeight: heightDimen(42),
    // backgroundColor:'red'
  },
  balanceTextTotal: {
    marginLeft: widthDimen(25),
    color: Colors.white,
    fontSize: areaDimen(15),
    fontFamily: Fonts.semibold,
    lineHeight: heightDimen(18),
    letterSpacing: widthDimen(-0.28),
    position: 'absolute',
    marginTop: heightDimen(43),
  },
  editIconStyle: {
    width: 15,
    height: 15,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  editIconStyle1: {
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  menuItemStyle: {
    width: Dimensions.get('screen').width > 360 ? 65 : 57,
    backgroundColor: Colors.lightBg,
    borderRadius: 10,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginHorizontal: '1%',
    paddingVertical: 5,
  },
  coinsListStyle: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  balanceViewStyle: {
    alignSelf: 'flex-end',
    width: '50%',
  },
  balanceText: {
    alignSelf: 'flex-end',
    fontFamily: Fonts.regular,
    textAlign: 'right',
    fontSize: 13,
  },
  coinStyle: {
    height: 30,
    width: 30,
    borderRadius: 15,
  },
  mainCardContainer: {
    minHeight: heightDimen(70),
    borderRadius: areaDimen(12),
    backgroundColor: 'red',
    marginBottom: heightDimen(10),
    paddingHorizontal: widthDimen(12),
    paddingVertical: heightDimen(12),
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor:ThemeManager.colors.shadowColor,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.05,
    elevation: 4,
    marginHorizontal:widthDimen(5)
  },
  coinBalanceFiat: {
    alignSelf: 'flex-end',
    lineHeight: heightDimen(19),
    fontSize: areaDimen(16),
    fontFamily: Fonts.medium,
    textAlign: 'right',
  },
  coinPriceStyle: {
    alignSelf: 'flex-end',
    lineHeight: heightDimen(18),
    fontSize: areaDimen(14),
    fontFamily: Fonts.medium,
  },
  graphImage: {
    height: 40,
    width: 150,
    resizeMode: 'contain',
  },
  coinListWrapStyle: {
    marginTop: heightDimen(12),
    paddingBottom: heightDimen(140),
    flexGrow: 1,
    marginHorizontal: 10,
    paddingTop:heightDimen(10)
  },
  noCoinText: {
    textAlign: 'center',
    fontSize: areaDimen(16),
    fontFamily: Fonts.regular,
  },
  coinNameStyle: {
    height: 30,
    width: 30,
    backgroundColor: Colors.buttonColor2,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
  },
  fiatText: {
    color: Colors.lightGrey2,
    fontFamily: Fonts.regular,
    fontSize: 11,
  },
  graphStyle: {
    width: '25%',
    marginRight: 10,
    alignSelf: 'flex-start',
  },
  manageBtnStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  manageBtnImg: {
    height: 14,
    width: 14,
    resizeMode: 'contain',
    tintColor: ThemeManager.colors.textColor,
    marginRight: 5,
  },
  assetsText: {
    color: ThemeManager.colors.textColor,
    fontSize: 16,
    fontFamily: fonts.semibold,
  },
  subView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    marginHorizontal: 15,
  },
  subContainer: {
    width: '100%',
    marginTop: 20,
    borderRadius: 10,
    justifyContent: 'center',
    paddingVertical: 5,
  },
  flexRow: {flexDirection: 'row', justifyContent: 'space-evenly'},
  okText: {
    color: Colors.white,
    fontSize: 16,
    fontFamily: fonts.regular,
    marginTop: 2,
  },
  refreshBtn: {
    alignSelf: 'flex-end',
    marginTop: -30,
    marginRight: -10,
  },
});
