import {StyleSheet, Text, View} from 'react-native';
import React from 'react';
import {
  BackupOptions,
  BuyHistory,
  BuyTransactionDetail,
  CoinHistory,
  DappBrowser,
  ExportPrivateKeys,
  Login,
  ResetConfirmPin,
  ResetCreatePIN,
  Security,
  SendCryptoContacts,
  Splash,
  SplashAppName,
  ConfirmPin,
  Congrats,
  CreateNewWallet,
  CreateOrImportWallet,
  CreatePIN,
  CreateWallet,
  CurrencyPreference,
  DappBrowserSwap,
  DappBrowserSwapc,
  DepositScreen,
  EditContact,
  EditWallet,
  Epay,
  FaceID,
  Gainer,
  GetSupport,
  History,
  Hot,
  ImportWallet,
  Linkview,
  Liquidity,
  LiquiditySelectToken,
  Loader,
  Loser,
  ManageWallet,
  MultiSender,
  MultiSenderBNB,
  MultiSenderEth,
  MultiSenderEthToken,
  MultiSenderMatic,
  MultiWalletImportSingleCoin,
  MultiWalletList,
  MultiWalletOptions,
  Notification,
  QrCode,
  RecoveryPhrase,
  Recipient,
  RegisterNow,
  RemoveLiquidity,
  RmLiquidityConfirm,
  SaveContact,
  ScanQr,
  SelectBlockchain,
  SelectLanguage,
  Send,
  SendBNB,
  SendBTC,
  SendETH,
  SendMATIC,
  SendTRX,
  SendSOL,
  Setting,
  Signup,
  StakingPools,
  SwapLiquidity,
  SwapNew,
  SwapScreen,
  SwapSettings,
  SwapTab,
  TermsandPrivacy,
  TransactionDetail,
  UserDetail,
  VerifyPhrase,
  WalletOption,
  WalletSequrity,
  WalletSequrityConfirm,
  AddNewContacts,
  AddToken,
  ApplyCard,
  ApplyCardWelcomeScreen,
  CardHistoryDetail,
  CardInfo,
  CardManage,
  CardSetting,
  KycShufti,
  NfcDemo,
  SaitaCardApplyForm,
  SaitaCardBinanceQr,
  SaitaCardBlack,
  SaitaCardChangePassword,
  SaitaCardDashBoard,
  SaitaCardDeposit,
  SaitaCardDepositBinance,
  SaitaCardDepositQr,
  SaitaCardDiamond,
  SaitaCardEpay,
  SaitaCardForgot,
  SaitaCardGold,
  SaitaCardHistory,
  SaitaCardLogin,
  SaitaCardNewPassword,
  SaitaCardPayOption,
  SaitaCardTransaction,
  SaitaCardWelcome,
  SaitaCardsInfo,
  SaitaProSupport,
  WelcomeScreen,
  ChangePassCode1,
  HourChanges,
  ConfirmSecurityPin,
  ChooseLanguage,
  SecureWallet,
  confirmTransaction,
  CountryCodes,
  SaitaVirtualForm,
  ChangePassword,
} from '../Components/Screens';
import ConnectWithDapp2 from '../Components/Screens/ConnectWithDapp/ConnectWithDapp2';
import SaitaCardHyperKycForm from '../Components/Screens/SaitaCardHyperKyc/SaitaCardHyperKycForm';
import CoinHome from '../Components/Screens/CoinHome/CoinHome';
import SaitaCardApplyPhysicalCard from '../Components/Screens/SaitaCardApplyPhysicalCard/SaitaCardApplyPhysicalCard';
import MultiSenderSTC from '../Components/Screens/MultiSenderSTC/MultiSenderSTC';
import SendSTC from '../Components/Screens/SendSTC/SendSTC';
import Stake from '../Components/Screens/StakeScreen/Stake';
import Trade from '../Components/Screens/Trade/Trade';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {setNavigationReference} from '../navigationsService';
import {NavigationStrings} from './NavigationStrings';
import TabRoutes from './TabRoutes';
import { NavigationContainer } from '@react-navigation/native';
import CardKyc from '../Components/Screens/Cards/CardKYC/CardKyc';
import AfterApplyDetails from '../Components/Screens/Cards/AfterApplyDetails/AfterApplyDetails';
import VaultTransactionHistory from '../Components/Screens/VaultTransactionHistory/VaultTransactionHistory';

const Stack = createNativeStackNavigator();
const Routes = () => {
  const scenes = [
    {key: NavigationStrings.Splash, component: Splash},
    {key: NavigationStrings.SplashAppName, component: SplashAppName},
    {key: NavigationStrings.Login, component: Login},
    {key: NavigationStrings.ResetCreatePIN, component: ResetCreatePIN},
    {key: NavigationStrings.DappBrowser, component: DappBrowser},
    {key: NavigationStrings.ResetConfirmPin, component: ResetConfirmPin},
    {key: NavigationStrings.BuyHistory, component: BuyHistory},
    {key: NavigationStrings.BackupOptions, component: BackupOptions},
    {key: NavigationStrings.ExportPrivateKeys, component: ExportPrivateKeys},
    {key: NavigationStrings.SendCryptoContacts, component: SendCryptoContacts},
    {key: NavigationStrings.CoinHistory, component: CoinHistory},
    {
      key: NavigationStrings.BuyTransactionDetail,
      component: BuyTransactionDetail,
    },
    {key: NavigationStrings.Security, component: Security},
    {key: NavigationStrings.ChangePassCode1, component: ChangePassCode1},
    {key: NavigationStrings.Signup, component: Signup},
    {key: NavigationStrings.Loser, component: Loser},
    {key: NavigationStrings.HourChanges, component: HourChanges},
    {key: NavigationStrings.VerifyPhrase, component: VerifyPhrase},
    {key: NavigationStrings.HistoryComponent, component: History},
    {key: NavigationStrings.ConfirmPin, component: ConfirmPin},
    {key: NavigationStrings.WalletSequrity, component: WalletSequrity},
    {key: NavigationStrings.SaitaProSupport, component: SaitaProSupport},
    {
      key: NavigationStrings.WalletSequrityConfirm,
      component: WalletSequrityConfirm,
    },
    {
      key: NavigationStrings.CreateOrImportWallet,
      component: CreateOrImportWallet,
    },
    {key: NavigationStrings.Setting, component: Setting},
    {key: NavigationStrings.Congrats, component: Congrats},
    {key: NavigationStrings.FaceID, component: FaceID},
    {key: NavigationStrings.EditWallet, component: EditWallet},
    {key: NavigationStrings.CreatePIN, component: CreatePIN},
    {key: NavigationStrings.ConfirmSecurityPin, component: ConfirmSecurityPin},
    {key: NavigationStrings.SaitaCardForgot, component: SaitaCardForgot},
    {
      key: NavigationStrings.SaitaCardNewPassword,
      component: SaitaCardNewPassword,
    },
    {
      key: NavigationStrings.SaitaCardChangePassword,
      component: SaitaCardChangePassword,
    },
    {key: NavigationStrings.SaitaCardEpay, component: SaitaCardEpay},
    {key: NavigationStrings.CardSetting, component: CardSetting},
    {key: NavigationStrings.WelcomeScreen, component: WelcomeScreen},
    {key: NavigationStrings.SelectLanguage, component: SelectLanguage},
    {key: NavigationStrings.ChooseLanguage, component: ChooseLanguage},
    {key: NavigationStrings.CreateWallet, component: CreateWallet},
    {key: NavigationStrings.ManageWallet, component: ManageWallet},
    {key: NavigationStrings.ImportWallet, component: ImportWallet},
    {key: NavigationStrings.CreateNewWallet, component: CreateNewWallet},
    {key: NavigationStrings.SecureWallet, component: SecureWallet},
    {key: NavigationStrings.RecoveryPhrase, component: RecoveryPhrase},
    {key: NavigationStrings.GetSupport, component: GetSupport},
    {key: NavigationStrings.Gainer, component: Gainer},
    {key: NavigationStrings.SwapScreen, component: SwapScreen},
    {key: NavigationStrings.StakingPools, component: StakingPools},
    {key: NavigationStrings.SendETH, component: SendETH},
    {key: NavigationStrings.SendMATIC, component: SendMATIC},
    {key: NavigationStrings.SendBNB, component: SendBNB},
    {key: NavigationStrings.SendBTC, component: SendBTC},
    {key: NavigationStrings.SendTRX, component: SendTRX},
    {key: NavigationStrings.SendSOL, component: SendSOL},
    {key: NavigationStrings.confirmTransaction, component: confirmTransaction},
    {key: NavigationStrings.Hot, component: Hot},
    {key: NavigationStrings.Send, component: Send},
    {key: NavigationStrings.QrCode, component: QrCode},
    {key: NavigationStrings.EditContact, component: EditContact},
    {key: NavigationStrings.AddNewContacts, component: AddNewContacts},
    {key: NavigationStrings.AddToken, component: AddToken},
    {key: NavigationStrings.SaveContact, component: SaveContact},
    {key: NavigationStrings.Epay, component: Epay},
    {key: NavigationStrings.MultiWalletOptions, component: MultiWalletOptions},
    {
      key: NavigationStrings.MultiWalletImportSingleCoin,
      component: MultiWalletImportSingleCoin,
    },
    {key: NavigationStrings.Linkview, component: Linkview},
    {key: NavigationStrings.Loader, component: Loader},
    {key: NavigationStrings.CurrencyPreference, component: CurrencyPreference},
    {key: NavigationStrings.Notification, component: Notification},
    {key: NavigationStrings.TransactionDetail, component: TransactionDetail},
    {key: NavigationStrings.ScanQr, component: ScanQr},
    {key: NavigationStrings.SelectBlockchain, component: SelectBlockchain},
    {key: NavigationStrings.MultiSender, component: MultiSender},
    {key: NavigationStrings.MultiSenderEth, component: MultiSenderEth},
    {key: NavigationStrings.MultiSenderBNB, component: MultiSenderBNB},
    {key: NavigationStrings.MultiSenderMatic, component: MultiSenderMatic},
    {
      key: NavigationStrings.MultiSenderEthToken,
      component: MultiSenderEthToken,
    },
    {key: NavigationStrings.Recipient, component: Recipient},
    {key: NavigationStrings.MultiWalletList, component: MultiWalletList},
    {key: NavigationStrings.WalletOption, component: WalletOption},
    {key: NavigationStrings.SwapTab, component: SwapTab},
    {key: NavigationStrings.SwapLiquidity, component: SwapLiquidity},
    {key: NavigationStrings.Liquidity, component: Liquidity},
    {key: NavigationStrings.DappBrowserSwap, component: DappBrowserSwap},
    {key: NavigationStrings.DappBrowserSwapc, component: DappBrowserSwapc},
    {key: NavigationStrings.Stake, component: Stake},
    {key: NavigationStrings.SwapSettings, component: SwapSettings},
    {key: NavigationStrings.TermsandPrivacy, component: TermsandPrivacy},
    {key: NavigationStrings.SwapNew, component: SwapNew},
    {
      key: NavigationStrings.LiquiditySelectToken,
      component: LiquiditySelectToken,
    },
    {key: NavigationStrings.RemoveLiquidity, component: RemoveLiquidity},
    {key: NavigationStrings.RmLiquidityConfirm, component: RmLiquidityConfirm},
    {key: NavigationStrings.SaitaCardDashBoard, component: SaitaCardDashBoard},
    {key: NavigationStrings.CardInfo, component: CardInfo},
    {key: NavigationStrings.CardManage, component: CardManage},
    {
      key: NavigationStrings.ApplyCardWelcomeScreen,
      component: ApplyCardWelcomeScreen,
    },
    {key: NavigationStrings.ApplyCard, component: ApplyCard},
    {key: NavigationStrings.DepositScreen, component: DepositScreen},
    {key: NavigationStrings.RegisterNow, component: RegisterNow},
    {key: NavigationStrings.UserDetail, component: UserDetail},
    {key: NavigationStrings.SaitaCardWelcome, component: SaitaCardWelcome},
    {key: NavigationStrings.SaitaCardsInfo, component: SaitaCardsInfo},
    {key: NavigationStrings.SaitaCardBlack, component: SaitaCardBlack},
    {key: NavigationStrings.SaitaCardGold, component: SaitaCardGold},
    {key: NavigationStrings.SaitaCardDiamond, component: SaitaCardDiamond},
    {key: NavigationStrings.SaitaCardDeposit, component: SaitaCardDeposit},
    {key: NavigationStrings.CardHistoryDetail, component: CardHistoryDetail},
    {key: NavigationStrings.SaitaCardHistory, component: SaitaCardHistory},
    {key: NavigationStrings.SaitaCardApplyForm, component: SaitaCardApplyForm},
    {key: NavigationStrings.SaitaCardPayOption, component: SaitaCardPayOption},
    {key: NavigationStrings.SaitaCardDepositQr, component: SaitaCardDepositQr},
    {
      key: NavigationStrings.SaitaCardDepositBinance,
      component: SaitaCardDepositBinance,
    },
    {key: NavigationStrings.SaitaCardBinanceQr, component: SaitaCardBinanceQr},
    {
      key: NavigationStrings.SaitaCardTransaction,
      component: SaitaCardTransaction,
    },
    {key: NavigationStrings.ConnectWithDapp, component: ConnectWithDapp2},
    {key: NavigationStrings.KycShufti, component: KycShufti},
    {key: NavigationStrings.CountryCodes, component: CountryCodes},
    {key: NavigationStrings.SaitaCardLogin, component: SaitaCardLogin},
    {key: NavigationStrings.TradeSwap, component: Trade},
    {key: NavigationStrings.NfcDemo, component: NfcDemo},
    {
      key: NavigationStrings.SaitaCardHyperKycForm,
      component: SaitaCardHyperKycForm,
    },
    {key: NavigationStrings.CoinHome, component: CoinHome},
    {
      key: NavigationStrings.SaitaCardApplyPhysicalCard,
      component: SaitaCardApplyPhysicalCard,
    },
    {key: NavigationStrings.SaitaVirtualForm, component: SaitaVirtualForm},
    {key: NavigationStrings.SendSTC, component: SendSTC},
    {key: NavigationStrings.MultiSenderSTC, component: MultiSenderSTC},
    {key: NavigationStrings.CardKyc, component: CardKyc},
    {key: NavigationStrings.AfterApplyDetails, component: AfterApplyDetails},
    {key: NavigationStrings.VaultTransactionHistory, component: VaultTransactionHistory},

  ];

  return (
    <NavigationContainer ref={setNavigationReference}>
      <Stack.Navigator
        screenOptions={{
          gestureEnabled: false,
          headerShown: false,
          animation: 'ios',
        }}>
        {scenes.map(val => (
          <Stack.Screen name={val.key} component={val.component} />
        ))}
        <Stack.Screen name={NavigationStrings.Main} component={TabRoutes} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default Routes;

const styles = StyleSheet.create({});
